/* test_gguf_gate.c - P3 PARITY GATE 1 + PARITY GATE 2 on the committed tiny
 * fixtures (test-dev unit).
 *
 * THE FIXTURE PAIR
 *   tests/fixtures/tiny_st/            the safetensors checkpoint (generated by
 *                                      make_tiny_checkpoint.py --aligned-dims)
 *   tests/fixtures/tiny_gguf/          single-shard GGUF (Q8_0 trunk, IQ1_S
 *                                      experts, F32 vectors)
 *   tests/fixtures/tiny_gguf_multi/    3 shards, shard 1 metadata-only, SAME
 *                                      weights
 *   tests/fixtures/tiny_gguf_bf16trunk/ the BIT-EXACT SUB-GATE variant: trunk
 *                                      written as F32 holding the ST path's
 *                                      bf16 values widened (the engine's
 *                                      F32->bf16 RNE dequant is the identity on
 *                                      bf16-representable values, so the
 *                                      engine's trunk bytes equal the ST
 *                                      file's bf16 bytes bit-for-bit)
 *   tests/fixtures/gguf_gate2_golden.bin  per-expert python references computed
 *                                      FROM THE SAME GGUF IQ1_S BYTES (see
 *                                      tools/ref_gguf_experts.py)
 *
 * WHAT IS ASSERTED
 *   A. fixture reader sanity: every GGUF fixture opens, the tensor counts /
 *      per-dim shapes / ggml types / split keys match, the D7 quirk arrays
 *      (type-5 elements, 4 bytes) parse, the tokenizer metadata walks, the
 *      contract table validates every tensor, the shard-1 config matches the
 *      ST config.json.
 *   B. BIT-EXACT SUB-GATE (io isolation): dequantizing the bf16trunk fixture's
 *      trunk through the ENGINE's F32->bf16 RNE dequant reproduces the ST
 *      file's bf16 bytes bit-for-bit (large matrices, embed, lm_head, the
 *      composite kv_b reassembly, A_log with the zero tail, and the folded
 *      *_res_score pairs). The encodings MATCH, so any io bug would show as a
 *      bit difference here, with no quantization noise to hide behind.
 *   C. PARITY GATE 2 (D2 hard gate): the engine's expert admit+matmul chain
 *      (K3GgufExpertSrc -> k3_matmul_mxfp4 -> k3_situ_glu) compared per expert
 *      against the golden's fp32 reference (IQ1_S dequant -> fp32 matmul) and
 *      its requant mirror (dequant -> MXFP4 requant -> matmul). The engine must
 *      sit at the requant mirror within fp32 accumulation tolerance (tight
 *      bound), and its distance to the fp32 reference must stay within the
 *      golden's OWN measured requant noise class (2x + slack) - the D2
 *      self-consistency criterion. Router selections must match the golden's.
 *   D. FULL-MODEL GATES: the complete 13-layer forward through the engine ops
 *      (k3_decoder_layer_inc) on (i) the ST fixture vs tiny_st/ref_logits.json,
 *      (ii) the single-shard GGUF vs its same-bytes reference, (iii) the
 *      multi-shard GGUF vs its same-bytes reference - all within the repo
 *      budget 1.2e-7*sqrt(hidden)*50; (iv) single vs multi MUST be bit-identical
 *      (shard layout is io-transparent); (v) the bf16trunk fixture (bound
 *      through k3_bind_layer_mem with a bf16eq finder, since the map's contract
 *      table demands Q8_0 for trunk rows - a design choice, see the report) vs
 *      its same-bytes reference within budget; (vi) bf16trunk vs ST forwards
 *      differ ONLY by the expert encodings, bounded by the measured Gate-2
 *      class (2x the python-measured 0.19 rel-L2).
 *
 * The real-file gate (K3_GGUF_REAL) is NOT needed here: every fixture is
 * committed and the gates are weightless-green in CI.
 */
#define _POSIX_C_SOURCE 200809L

#include <math.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "json.h"
#include "k3.h"
#include "k3_cfg.h"
#include "k3_gguf.h"
#include "k3_gguf_dequant.h"
#include "k3_gguf_expert.h"
#include "k3_gguf_map.h"
#include "k3_mxfp4_quant.h"
#include "k3_st.h"

/* ------------------------------------------------------------------ harness */
static int fails;

static void ck(int cond, const char *fmt, ...)
{
    char msg[512];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(msg, sizeof msg, fmt, ap);
    va_end(ap);
    if (cond) {
        printf("  ok    %s\n", msg);
        return;
    }
    printf("  FAIL  %s\n", msg);
    fprintf(stderr, "  FAIL  %s\n", msg);
    fails++;
}

static double rel_l2(const float *a, const float *b, int n)
{
    double sa = 0.0, sd = 0.0;
    for (int i = 0; i < n; i++) {
        const double da = a[i], db = b[i];
        sa += db * db;
        const double d = da - db;
        sd += d * d;
    }
    return sqrt(sd / (sa > 0.0 ? sa : 1.0));
}

static double max_rel(const float *a, const float *b, int n, double scale)
{
    double worst = 0.0;
    for (int i = 0; i < n; i++) {
        const double d = fabs((double)a[i] - (double)b[i]);
        if (d > worst) worst = d;
    }
    return worst / (scale > 0.0 ? scale : 1.0);
}

static uint32_t rd32(const unsigned char *p)
{
    return (uint32_t)p[0] | (uint32_t)p[1] << 8 | (uint32_t)p[2] << 16 |
           (uint32_t)p[3] << 24;
}

static void rd_floats(const unsigned char *p, int n, float *out)
{
    for (int i = 0; i < n; i++) {
        uint32_t u = rd32(p + 4 * i);
        memcpy(&out[i], &u, 4);
    }
}

static void rd_i32s(const unsigned char *p, int n, int32_t *out)
{
    for (int i = 0; i < n; i++) {
        uint32_t u = rd32(p + 4 * i);
        memcpy(&out[i], &u, 4);
    }
}

/* ------------------------------------------------------- A: reader sanity */
static void open_fixture(const char *dir, int want_shards, int want_tensors,
                         int trunk_is_f32, const char *label)
{
    printf("== fixture: %s ==\n", label);
    K3Gguf g;
    if (k3_gguf_open(&g, dir) != 0) {
        ck(0, "open %s", label);
        return;
    }
    ck(g.nshard == want_shards, "%s: %d shards", label, want_shards);
    ck(g.nt == want_tensors, "%s: %d tensors", label, want_tensors);
    ck(g.alignment == 32, "%s: alignment 32", label);

    const K3GgufKV *k = k3_gguf_kv(&g, "split.no");
    ck(k && k->type == 2 && k->v.u == 0, "%s: split.no u16 0", label);
    k = k3_gguf_kv(&g, "split.count");
    ck(k && k->type == 2 && k->v.u == (uint64_t)want_shards, "%s: split.count u16 %d",
       label, want_shards);
    k = k3_gguf_kv(&g, "split.tensors.count");
    ck(k && k->type == 5 && k->v.u == (uint64_t)want_tensors,
       "%s: split.tensors.count i32 %d", label, want_tensors);

    /* the D7 quirk: ARRAY with type-5 elements, 4 bytes each */
    k = k3_gguf_kv(&g, "kimi-k3.attention.head_count_kv");
    ck(k && k->type == 9 && k->v.a.et == 5 && k->v.a.n == 13 && k->v.a.nbytes == 52,
       "%s: head_count_kv quirk array (type-5, 4-byte elements)", label);
    if (k && k->v.a.d) {
        const uint32_t *hc = (const uint32_t *)k->v.a.d;
        ck(hc[0] == 0 && hc[1] == 0 && hc[2] == 0 && hc[3] == 1 && hc[4] == 0 &&
               hc[6] == 0 && hc[7] == 1 && hc[11] == 1 && hc[12] == 1,
           "%s: head_count_kv values {0,0,0,1,0,0,0,1,0,0,0,1,1}", label);
    }

    K3Cfg c;
    static int fa[64];
    if (!k3_gguf_cfg(&g, &c, fa, 64)) {
        ck(0, "%s: shard-1 config load", label);
        k3_gguf_close(&g);
        return;
    }
    ck(c.hidden == 128 && c.n_layers == 13 && c.vocab == 256, "%s: cfg dims", label);
    ck(c.kda_heads == 4 && c.kda_head_dim == 32 && c.conv_k == 4, "%s: cfg kda", label);
    ck(c.q_lora == 64 && c.kv_lora == 32 && c.qk_nope == 32 && c.qk_rope == 8 &&
           c.v_head == 32,
       "%s: cfg mla", label);
    ck(c.n_experts == 8 && c.topk == 2 && c.n_shared == 2 && c.latent == 64 &&
           c.moe_inter == 64,
       "%s: cfg moe", label);
    ck(c.first_dense == 1 && c.dense_inter == 96 && c.attn_res_block == 3,
       "%s: cfg dense/attnres", label);
    ck(c.n_full_attn == 4 && fa[0] == 4 && fa[1] == 8 && fa[2] == 12 && fa[3] == 13,
       "%s: cfg fa list {4,8,12,13}", label);
    ck(c.situ_b1 == 4.0f && c.situ_b2 == 25.0f && c.rms_eps == 1e-5f, "%s: cfg betas/eps",
       label);
    int nmla = 0;
    for (int i = 0; i < c.n_layers; i++)
        if (k3_is_mla(&c, i)) nmla++;
    ck(nmla == 4, "%s: 4 MLA layers", label);

    /* the tokenizer metadata walk (k3_gguf_tok re-walks shard 1) */
    {
        K3GgufTok tok;
        if (k3_gguf_tok(&g, &tok) != 0) {
            ck(0, "%s: tokenizer metadata walk", label);
        } else {
            ck(tok.ntok == 256 && tok.nmerges == 127 && tok.nttype == 256,
               "%s: tokenizer 256 tokens / 127 merges / 256 types", label);
            ck(!strcmp(tok.model, "gpt2") && !strcmp(tok.pre, "kimi-k2"),
               "%s: tokenizer model gpt2 pre kimi-k2", label);
            ck(tok.vocab_size == 256, "%s: tokenizer vocab 256", label);
            k3_gguf_tok_free(&tok);
        }
    }

    /* spot-checked tensors: per-dim shape, ggml type, on-disk nbytes */
    const K3Tensor *t = k3_gguf_find(&g, "token_embd.weight");
    ck(t && t->ndim == 2 && t->shape[0] == 128 && t->shape[1] == 256 &&
           (trunk_is_f32
                ? (g.gtype[t - g.t] == K3_GGUF_TYPE_F32 && t->nbytes == 128 * 256 * 4)
                : (g.gtype[t - g.t] == K3_GGUF_TYPE_Q8_0 &&
                   t->nbytes == 128 / 32 * 34 * 256)),
       "%s: token_embd [128,256] (%s)", label, trunk_is_f32 ? "F32" : "Q8_0");
    t = k3_gguf_find(&g, "blk.1.ffn_gate_exps.weight");
    ck(t && t->ndim == 3 && t->shape[0] == 64 && t->shape[1] == 64 && t->shape[2] == 8 &&
           g.gtype[t - g.t] == K3_GGUF_TYPE_IQ1_S && t->nbytes == 50 * 64 * 8 &&
           t->nbytes % 8 == 0,
       "%s: blk.1.ffn_gate_exps IQ1_S [64,64,8] 25600 B", label);
    t = k3_gguf_find(&g, "blk.0.ffn_down.weight");
    ck(t && t->shape[0] == 96 && t->shape[1] == 128, "%s: dense blk.0.ffn_down [96,128]",
       label);
    t = k3_gguf_find(&g, "blk.0.ssm_f_b.weight");
    ck(t && t->shape[0] == 32 && t->shape[1] == 128, "%s: kda blk.0.ssm_f_b [32,128]",
       label);
    t = k3_gguf_find(&g, "blk.11.attn_k_b.weight");
    ck(t && t->ndim == 3 && t->shape[0] == 32 && t->shape[1] == 32 && t->shape[2] == 4,
       "%s: mla blk.11.attn_k_b [32,32,4]", label);
    if (trunk_is_f32) {
        t = k3_gguf_find(&g, "blk.0.attn_q.weight");
        ck(t && g.gtype[t - g.t] == K3_GGUF_TYPE_F32 && t->nbytes == 128 * 128 * 4,
           "%s: bf16eq variant trunk is F32", label);
    }

    if (!trunk_is_f32) {
        const int checked = k3_gguf_validate_all(&g, &c);
        ck(checked == want_tensors, "%s: contract table validates all %d tensors", label,
           want_tensors);
    }
    k3_gguf_close(&g);
}

/* ----------------------------------------- B: bit-exact trunk sub-gate */
/* The bf16trunk fixture's trunk (F32 = ST bf16 values widened) dequantized by
 * the ENGINE (F32->bf16 RNE) must reproduce the ST file's bf16 bytes exactly. */
static void run_bit_exact_trunk(const char *st_dir, const char *gg_dir)
{
    printf("== bit-exact trunk sub-gate (bf16trunk vs safetensors) ==\n");

    K3St st;
    if (k3_st_open(&st, st_dir) != 0) {
        ck(0, "open the safetensors fixture");
        return;
    }
    K3Gguf g;
    if (k3_gguf_open(&g, gg_dir) != 0) {
        ck(0, "open the bf16trunk fixture");
        k3_st_close(&st);
        return;
    }
    K3Cfg c;
    static int fa[64];
    if (!k3_gguf_cfg(&g, &c, fa, 64)) {
        ck(0, "bf16trunk config");
        k3_gguf_close(&g);
        k3_st_close(&st);
        return;
    }

    static unsigned char stbuf[1 << 20], raw[1 << 20];
    static uint16_t bf16[1 << 18];

    for (int ti = 0; ti < st.nt; ti++) {
        const K3Tensor *ts = &st.t[ti];
        const char *name   = ts->name;
        /* experts are Gate 2's variable; the res_proj side is checked through
         * its folded counterpart below */
        if (strstr(name, "block_sparse_moe.experts.")) continue;

        int layer      = -1;
        const char *lp = strstr(name, "layers.");
        if (lp) layer = atoi(lp + 7);
        char gname[160];
        if (k3_gguf_map_translate(&c, layer, name, gname, sizeof gname) != 0) {
            ck(0, "translate %s", name);
            continue;
        }
        if (!strcmp(gname, "(const ones)")) continue; /* the fold check below */

        const int is_res_norm = strstr(name, "res_norm.weight") != NULL;
        const int is_alog     = strstr(name, ".self_attn.A_log") != NULL;

        if (!strcmp(gname, "(composite kv_b)")) {
            /* reassemble the engine's kv_b from the GGUF halves, dequantized
             * F32->bf16, and require the ST bytes back exactly */
            char kb[96], vb[96];
            snprintf(kb, sizeof kb, "blk.%d.attn_k_b.weight", layer);
            snprintf(vb, sizeof vb, "blk.%d.attn_v_b.weight", layer);
            const K3Tensor *kt = k3_gguf_find(&g, kb);
            const K3Tensor *vt = k3_gguf_find(&g, vb);
            if (!kt || !vt) {
                ck(0, "kv_b halves present (L%d)", layer);
                continue;
            }
            const int64_t QN = c.qk_nope, VH = c.v_head, KL = c.kv_lora, H = c.n_heads;
            if (k3_gguf_read(&g, kt, raw) != kt->nbytes ||
                k3_gguf_read(&g, vt, raw + kt->nbytes) != vt->nbytes) {
                ck(0, "kv_b halves read (L%d)", layer);
                continue;
            }
            K3GgufTensor kg, vg;
            K3GgufExpect ex;
            memset(&kg, 0, sizeof kg);
            kg.ggml_type = K3_GGUF_TYPE_F32;
            kg.ndim      = 3;
            kg.ne[0]     = QN;
            kg.ne[1]     = KL;
            kg.ne[2]     = H;
            kg.nbytes    = kt->nbytes;
            kg.data      = raw;
            memset(&ex, 0, sizeof ex);
            ex.ndim  = 3;
            ex.ne[0] = QN;
            ex.ne[1] = KL;
            ex.ne[2] = H;
            if (k3_gguf_dequant(&kg, K3_GGUF_DEQ_BF16, bf16, &ex) != 0) {
                ck(0, "kv_b k half dequant (L%d)", layer);
                continue;
            }
            const uint16_t *ks = bf16;
            memset(&vg, 0, sizeof vg);
            vg.ggml_type = K3_GGUF_TYPE_F32;
            vg.ndim      = 3;
            vg.ne[0]     = KL;
            vg.ne[1]     = VH;
            vg.ne[2]     = H;
            vg.nbytes    = vt->nbytes;
            vg.data      = raw + kt->nbytes;
            memset(&ex, 0, sizeof ex);
            ex.ndim  = 3;
            ex.ne[0] = KL;
            ex.ne[1] = VH;
            ex.ne[2] = H;
            if (k3_gguf_dequant(&vg, K3_GGUF_DEQ_BF16, bf16 + H * KL * QN, &ex) != 0) {
                ck(0, "kv_b v half dequant (L%d)", layer);
                continue;
            }
            const uint16_t *vs = bf16 + H * KL * QN;
            static uint16_t kvb[8192];
            for (int64_t h = 0; h < H; h++) {
                for (int64_t i = 0; i < QN; i++)
                    for (int64_t j = 0; j < KL; j++)
                        kvb[(size_t)(h * (QN + VH) + i) * KL + j] =
                            ks[(size_t)(h * KL + j) * QN + i];
                for (int64_t i = 0; i < VH; i++)
                    memcpy(kvb + (size_t)(h * (QN + VH) + QN + i) * KL,
                           vs + (size_t)(h * VH + i) * KL, (size_t)KL * 2);
            }
            if (k3_st_read(&st, ts, stbuf) != ts->nbytes) {
                ck(0, "ST kv_b read (L%d)", layer);
                continue;
            }
            ck(ts->nbytes == (int64_t)(H * (QN + VH) * KL * 2) &&
                   memcmp(stbuf, kvb, (size_t)ts->nbytes) == 0,
               "kv_b composite bit-exact (L%d)", layer);
            continue;
        }

        const K3Tensor *tg = k3_gguf_find(&g, gname);
        if (!tg) {
            ck(0, "GGUF tensor %s present (engine %s)", gname, name);
            continue;
        }
        if (k3_st_read(&st, ts, stbuf) != ts->nbytes ||
            k3_gguf_read(&g, tg, raw) != tg->nbytes) {
            ck(0, "read %s", name);
            continue;
        }

        /* the folded res pairs: the GGUF norm side holds norm*proj; the engine
         * multiplies it by the const-1.0 proj side. Check the GGUF bytes equal
         * the fp32 product of the ST's norm and proj. */
        if (is_res_norm) {
            char proj_name[224];
            snprintf(proj_name, sizeof proj_name, "%.*sres_proj.weight",
                     (int)(strstr(name, "res_norm.weight") - name), name);
            const K3Tensor *tp = k3_st_find(&st, proj_name);
            if (!tp || k3_st_read(&st, tp, stbuf + ts->nbytes) != tp->nbytes) {
                ck(0, "ST res_proj %s read", proj_name);
                continue;
            }
            int same = 1;
            for (int64_t j = 0; j < c.hidden; j++) {
                float n, p;
                memcpy(&n, stbuf + 4 * j, 4);
                memcpy(&p, stbuf + ts->nbytes + 4 * j, 4);
                const float fold = n * p; /* fp32, same as the generator */
                float gf;
                memcpy(&gf, raw + 4 * j, 4);
                if (memcmp(&fold, &gf, 4) != 0) same = 0;
            }
            ck(same, "res fold bit-exact: GGUF %s == ST norm*proj", gname);
            continue;
        }

        if (ts->dtype == K3_DT_BF16) {
            /* trunk: the GGUF F32 bytes must be the ST bf16 values widened, and
             * the engine's F32->bf16 RNE dequant must give the ST bytes back */
            int widened = 1;
            for (int64_t j = 0; j < ts->nbytes / 2; j++) {
                uint16_t h16;
                memcpy(&h16, stbuf + 2 * j, 2);
                float f;
                memcpy(&f, raw + 4 * j, 4);
                uint32_t u;
                memcpy(&u, &f, 4);
                if ((u >> 16) != h16) widened = 0;
            }
            ck(widened, "GGUF F32 trunk == widened ST bf16 (%s)", name);
            K3GgufTensor gt;
            K3GgufExpect ex;
            memset(&gt, 0, sizeof gt);
            gt.ggml_type = K3_GGUF_TYPE_F32;
            gt.ndim      = ts->ndim;
            for (int d = 0; d < ts->ndim; d++) gt.ne[d] = ts->shape[d];
            gt.nbytes = tg->nbytes;
            gt.data   = raw;
            memset(&ex, 0, sizeof ex);
            ex.ndim = ts->ndim;
            for (int d = 0; d < ts->ndim; d++) ex.ne[d] = ts->shape[d];
            if (k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, bf16, &ex) != 0) {
                ck(0, "dequant %s", name);
                continue;
            }
            ck(memcmp(bf16, stbuf, (size_t)ts->nbytes) == 0,
               "engine F32->bf16 dequant bit-exact vs ST (%s)", name);
        } else if (is_alog) {
            /* ST ships [kda_head_dim] with a zero tail; the GGUF ships
             * [kda_heads]; the engine pads. The head prefix must match and the
             * ST tail must be zero. */
            int same = 1;
            for (int64_t j = 0; j < c.kda_heads; j++) {
                float a, b;
                memcpy(&a, stbuf + 4 * j, 4);
                memcpy(&b, raw + 4 * j, 4);
                if (memcmp(&a, &b, 4) != 0) same = 0;
            }
            for (int64_t j = c.kda_heads; j < c.kda_head_dim; j++) {
                float a;
                memcpy(&a, stbuf + 4 * j, 4);
                if (a != 0.0f) same = 0;
            }
            ck(same, "A_log: GGUF [kda_heads] == ST prefix, ST tail zero");
        } else {
            /* reqw vectors: identical F32 bytes */
            ck(ts->nbytes == tg->nbytes && memcmp(stbuf, raw, (size_t)ts->nbytes) == 0,
               "F32 vector bit-exact (%s)", name);
        }
    }
    k3_gguf_close(&g);
    k3_st_close(&st);
}

/* ------------------------------- C: PARITY GATE 2 (expert self-consistency) */
static void run_gate2(const char *gg_dir, const char *golden_path)
{
    printf("== parity gate 2: expert requant self-consistency (D2) ==\n");
    FILE *f = fopen(golden_path, "rb");
    if (!f) {
        ck(0, "open %s", golden_path);
        return;
    }
    unsigned char hdr[28];
    if (fread(hdr, 1, 28, f) != 28 || memcmp(hdr, "K3G2", 4) != 0) {
        ck(0, "gate2 golden header");
        fclose(f);
        return;
    }
    const uint32_t ncases = rd32(hdr + 8), nmoe = rd32(hdr + 12);
    const uint32_t E = rd32(hdr + 16), L = rd32(hdr + 20), I = rd32(hdr + 24);

    K3Gguf g;
    if (k3_gguf_open(&g, gg_dir) != 0) {
        ck(0, "open the gguf fixture for gate 2");
        fclose(f);
        return;
    }
    K3Cfg c;
    static int fa[64];
    if (!k3_gguf_cfg(&g, &c, fa, 64)) {
        ck(0, "gate2 config");
        fclose(f);
        k3_gguf_close(&g);
        return;
    }
    if ((uint32_t)c.hidden != E || (uint32_t)c.latent != L ||
        (uint32_t)c.moe_inter != I) {
        ck(0, "gate2 golden dims match the fixture");
        fclose(f);
        k3_gguf_close(&g);
        return;
    }
    {
        int nmoe_layers = 0;
        for (int i = 0; i < c.n_layers; i++)
            if (!k3_is_dense(&c, i)) nmoe_layers++;
        ck(ncases == (uint32_t)(nmoe_layers * c.n_experts) &&
               nmoe == (uint32_t)nmoe_layers,
           "gate2 golden case counts match the fixture (%u cases, %u MoE "
           "layers)",
           ncases, nmoe);
    }

    K3GgufExpertSrc es;
    if (k3_gguf_expert_src_init(&es, &g, &c, (int64_t)1 << 26) != 0) {
        ck(0, "expert source init");
        fclose(f);
        k3_gguf_close(&g);
        return;
    }

    static float z[256], fp32_out[256], req_out[256], gu[512], act[256], edn[256];
    double worst_tight = 0.0, worst_class = 0.0, worst_noise = 0.0;
    double best_noise = 1.0, class_sum = 0.0;
    int nclass = 0;
    unsigned char rec[4096];
    const size_t crec = 8 + 4 * (size_t)L * 3 + 4; /* + the noise float */
    for (uint32_t ci = 0; ci < ncases; ci++) {
        if (fread(rec, 1, crec, f) != crec) {
            ck(0, "gate2 golden case %u record", ci);
            break;
        }
        const uint32_t layer = rd32(rec), expert = rd32(rec + 4);
        rd_floats(rec + 8, (int)L, z);
        rd_floats(rec + 8 + 4 * (size_t)L, (int)L, fp32_out);
        rd_floats(rec + 8 + 8 * (size_t)L, (int)L, req_out);
        float noise;
        memcpy(&noise, rec + 8 + 12 * (size_t)L, 4);

        K3ExpertQ q;
        if (es.src.get(&es.src, (int)layer, (int)expert, &q) != 0) {
            ck(0, "expert get L%u e%u", layer, expert);
            continue;
        }
        k3_matmul_mxfp4(gu, z, q.p1, q.s1, (int)L, (int)I, K3_MXFP4_GROUP);
        k3_matmul_mxfp4(gu + I, z, q.p3, q.s3, (int)L, (int)I, K3_MXFP4_GROUP);
        k3_situ_glu(act, gu, (int)I, c.situ_b1, c.situ_b2);
        k3_matmul_mxfp4(edn, act, q.p2, q.s2, (int)I, (int)L, K3_MXFP4_GROUP);

        const double tight = rel_l2(edn, req_out, (int)L);
        const double class = rel_l2(edn, fp32_out, (int)L);
        if (tight > worst_tight) worst_tight = tight;
        if (class > worst_class) worst_class = class;
        if (noise > worst_noise) worst_noise = noise;
        if (noise < best_noise) best_noise = noise;
        class_sum += class;
        nclass++;
        /* D2 self-consistency: the engine sits at the requant mirror within
         * fp32 accumulation (the golden's mirror uses the same bytes and the
         * same requant math), and its distance to the fp32 reference is the
         * golden's OWN measured requant noise class - never a picked
         * tolerance. */
        if (tight > 1e-4) {
            ck(0, "case L%u e%u: engine vs requant-mirror rel-L2 %.3e > 1e-4", layer,
               expert, tight);
        }
        if (noise < 1e-4 || noise > 0.5) {
            ck(0, "case L%u e%u: golden requant noise %.4f out of class", layer, expert,
               noise);
        }
        if (class > 2.0 * noise + 1e-4) {
            ck(0,
               "case L%u e%u: engine vs fp32-ref rel-L2 %.4f > 2x requant "
               "noise %.4f",
               layer, expert, class, noise);
        }
    }
    printf("  cases %u, engine-vs-mirror worst %.3e (bound 1e-4)\n", ncases, worst_tight);
    printf("  requant class: golden min/mean/max %.4f/%.4f/%.4f, engine-vs-"
           "fp32ref worst %.4f\n",
           best_noise, class_sum / (nclass ? nclass : 1), worst_noise, worst_class);
    ck(worst_tight <= 1e-4, "gate 2: engine == requant mirror (fp32 class)");
    ck(worst_class <= 2.0 * worst_noise + 1e-4,
       "gate 2: engine within the golden's own requant noise class");

    /* router agreement: the golden captured the reference's selections on the
     * SAME gate bytes; the engine's k3_router must select identically */
    const size_t rrec = 4 + 4 * (size_t)E + 4 * (size_t)c.topk * 2;
    for (uint32_t li = 0; li < nmoe; li++) {
        if (fread(rec, 1, rrec, f) != rrec) {
            ck(0, "gate2 golden router record %u", li);
            break;
        }
        const uint32_t layer = rd32(rec);
        rd_floats(rec + 4, (int)E, z);
        int32_t idx_ref[K3_MAX_TOPK];
        float wt_ref[K3_MAX_TOPK];
        rd_i32s(rec + 4 + 4 * (size_t)E, c.topk, idx_ref);
        rd_floats(rec + 4 + 4 * (size_t)E + 4 * (size_t)c.topk, c.topk, wt_ref);

        char gname[96];
        snprintf(gname, sizeof gname, "blk.%u.ffn_gate_inp.weight", layer);
        const K3Tensor *gt = k3_gguf_find(&g, gname);
        snprintf(gname, sizeof gname, "blk.%u.exp_probs_b.bias", layer);
        const K3Tensor *bt = k3_gguf_find(&g, gname);
        if (!gt || !bt) {
            ck(0, "router tensors L%u", layer);
            continue;
        }
        static float gate[1 << 16], bias[256];
        if (k3_gguf_read(&g, gt, gate) != gt->nbytes ||
            k3_gguf_read(&g, bt, bias) != bt->nbytes) {
            ck(0, "router read L%u", layer);
            continue;
        }
        int idx_c[K3_MAX_TOPK];
        float wt_c[K3_MAX_TOPK];
        k3_router(idx_c, wt_c, z, gate, bias, (int)E, c.n_experts, c.topk, c.moe_renorm,
                  c.routed_scale);
        int same = idx_c[0] == idx_ref[0] && idx_c[1] == idx_ref[1];
        for (int j = 0; j < c.topk && same; j++) {
            const double d = fabs(wt_c[j] - wt_ref[j]);
            if (d > 1e-3 * fmax(fabs(wt_ref[j]), 1e-6)) same = 0;
        }
        ck(same, "router selection L%u matches the reference", layer);
    }

    k3_gguf_expert_src_free(&es);
    k3_gguf_close(&g);
    fclose(f);
}

/* ------------------------------------------- D: full-model forward gates */
/* The forward mirrors k3_run.c's non-incremental path exactly. */
typedef struct {
    K3LayerBind *lay; /* n_layers binds */
    int n_bound;
    K3ModelBind mb;
    K3ExpertSrc *exp_src;
    K3GgufBind *gguf; /* non-NULL: refill every layer via k3_gguf_bind_layer */
} Fwd;

static int forward(Fwd *w, const K3Cfg *c, const int *ids, int T, float *logits_last,
                   float *scratch, float *h, float *br, float *kstate)
{
    const int E       = c->hidden;
    const int maxb    = c->n_layers / c->attn_res_block + 2;
    const int P       = c->kda_heads * c->kda_head_dim;
    const size_t kper = (size_t)P * c->kda_head_dim + (size_t)3 * P * (c->conv_k - 1);

    for (int t = 0; t < T; t++)
        k3_embed_row(h + (size_t)t * E, w->mb.embed, w->mb.wdt, ids[t], E);
    memset(br, 0, (size_t)T * (size_t)maxb * (size_t)E * sizeof(float));
    memset(kstate, 0, kper * (size_t)w->n_bound * sizeof(float));
    int nb = 0;
    for (int L = 0; L < w->n_bound; L++) {
        if (w->gguf) {
            if (k3_gguf_bind_layer(w->gguf, L, &w->lay[L]) != 0) {
                fprintf(stderr, "gguf bind failed at layer %d\n", L);
                return -1;
            }
        }
        if (w->lay[L].lay.moe) {
            w->lay[L].moe.src        = w->exp_src;
            w->lay[L].moe.layer      = L;
            w->lay[L].moe.cache_only = 0;
        }
        k3_decoder_layer_inc(h, br, &nb, &w->lay[L].lay, c, L, T,
                             kstate + kper * (size_t)L, scratch, NULL, NULL, 0, 0);
    }
    if (w->mb.out_res_norm && w->mb.out_res_proj) {
        float *fold = scratch;
        float *src  = fold + E;
        for (int i = 0; i < E; i++)
            fold[i] = w->mb.out_res_norm[i] * w->mb.out_res_proj[i];
        for (int t = 0; t < T; t++) {
            for (int b = 0; b < nb; b++)
                memcpy(src + (size_t)b * E, br + ((size_t)t * maxb + b) * E,
                       (size_t)E * sizeof(float));
            memcpy(src + (size_t)nb * E, h + (size_t)t * E, (size_t)E * sizeof(float));
            k3_attn_res(h + (size_t)t * E, src, fold, nb + 1, E, c->rms_eps);
        }
    }
    float *nrm = scratch;
    k3_rmsnorm(nrm, h + (size_t)(T - 1) * E, w->mb.norm, E, c->rms_eps);
    k3_mmw(logits_last, nrm, w->mb.lm_head, w->mb.wdt, E, c->vocab);
    return 0;
}

static void *xmalloc(size_t n)
{
    void *p = malloc(n);
    if (!p) {
        fprintf(stderr, "oom (%zu bytes)\n", n);
        exit(3);
    }
    return p;
}

typedef struct {
    char path[1024];
    char label[64];
} Ref;

static int run_logits_gate(Fwd *w, const K3Cfg *c, const int *ids, int T, const Ref *ref,
                           const char *tag, float *scratch, float *h, float *br,
                           float *kstate, float *lg)
{
    if (forward(w, c, ids, T, lg, scratch, h, br, kstate) != 0) {
        ck(0, "%s: forward", tag);
        return -1;
    }
    char *rtxt = NULL;
    long rlen  = 0;
    FILE *f    = fopen(ref->path, "rb");
    if (!f) {
        ck(0, "%s: cannot open %s", tag, ref->path);
        return -1;
    }
    fseek(f, 0, SEEK_END);
    rlen = ftell(f);
    fseek(f, 0, SEEK_SET);
    rtxt = (char *)xmalloc((size_t)rlen + 1);
    if (fread(rtxt, 1, (size_t)rlen, f) != (size_t)rlen) {
        ck(0, "%s: short read of %s", tag, ref->path);
        free(rtxt);
        fclose(f);
        return -1;
    }
    fclose(f);
    rtxt[rlen]  = 0;
    char *arena = NULL;
    jval *root  = json_parse(rtxt, &arena);
    jval *jb    = json_get(root, "logits_bits");
    if (!jb || jb->len != c->vocab) {
        ck(0, "%s: ref json shape", tag);
        free(arena);
        free(rtxt);
        return -1;
    }
    float *r = (float *)xmalloc((size_t)c->vocab * sizeof(float));
    for (int i = 0; i < jb->len; i++) {
        uint32_t u = (uint32_t)jb->kids[i]->num;
        memcpy(&r[i], &u, 4);
    }
    jval *ja              = json_get(root, "argmax");
    const int want_argmax = ja ? (int)ja->num : -1;

    double scale = 1e-30;
    for (int i = 0; i < c->vocab; i++)
        if (fabs((double)r[i]) > scale) scale = fabs((double)r[i]);
    const double budget = 1.2e-7 * sqrt((double)c->hidden) * 50.0;
    const double rel    = max_rel(lg, r, c->vocab, scale);
    int ca              = 0;
    for (int i = 1; i < c->vocab; i++)
        if (lg[i] > lg[ca]) ca = i;
    printf("  %-28s argmax %d vs %d, max|diff|/max|ref| %.3e (budget %.1e)\n", tag, ca,
           want_argmax, rel, budget);
    ck(ca == want_argmax, "%s: argmax matches the reference", tag);
    ck(rel <= budget, "%s: logits within the repo budget", tag);
    free(r);
    free(arena);
    free(rtxt);
    return ca;
}

/* ST-side experts -> fp32 resident banks (dequantized MXFP4, the engine's
 * canonical w1/w3 [moe_inter][latent], w2 [latent][moe_inter] layout) */
static void load_st_experts(const K3St *st, const K3Cfg *c, int layer, float *b1,
                            float *b3, float *b2)
{
    const size_t p13 = (size_t)c->moe_inter * c->latent;
    const size_t p2  = (size_t)c->latent * c->moe_inter;
    char name[224];
    static unsigned char packed[1 << 20];
    for (int e = 0; e < c->n_experts; e++) {
        for (int m = 0; m < 3; m++) {
            const char *which = m == 0 ? "w1" : (m == 1 ? "w2" : "w3");
            float *dst        = m == 0   ? b1 + (size_t)e * p13
                                : m == 1 ? b2 + (size_t)e * p2
                                         : b3 + (size_t)e * p13;
            snprintf(name, sizeof name,
                     "language_model.model.layers.%d.block_sparse_moe.experts."
                     "%d.%s.weight_packed",
                     layer, e, which);
            const K3Tensor *tp = k3_st_find(st, name);
            snprintf(name, sizeof name,
                     "language_model.model.layers.%d.block_sparse_moe.experts."
                     "%d.%s.weight_scale",
                     layer, e, which);
            const K3Tensor *ts = k3_st_find(st, name);
            if (!tp || !ts) {
                fprintf(stderr, "missing ST expert L%d e%d %s\n", layer, e, which);
                exit(3);
            }
            k3_st_read(st, tp, packed);
            k3_st_read(st, ts, packed + (size_t)tp->nbytes);
            const int rows = m == 1 ? (int)c->latent : (int)c->moe_inter;
            const int cols = m == 1 ? (int)c->moe_inter : (int)c->latent;
            k3_mxfp4_dequant(dst, packed, packed + (size_t)tp->nbytes, rows, cols / 2,
                             K3_MXFP4_GROUP);
        }
    }
}

/* the ST full-model gate: k3_bind_layer + fp32 expert banks */
static void run_st_forward_gate(const char *st_dir, const K3Cfg *c, const int *ids, int T,
                                const Ref *ref, float *scratch, float *h, float *br,
                                float *kstate, float *lg)
{
    printf("== full-model gate: safetensors path ==\n");
    K3St st;
    if (k3_st_open(&st, st_dir) != 0) {
        ck(0, "open the ST fixture");
        return;
    }
    Fwd w;
    memset(&w, 0, sizeof w);
    w.n_bound = c->n_layers;
    w.lay     = (K3LayerBind *)xmalloc((size_t)c->n_layers * sizeof(K3LayerBind));
    for (int L = 0; L < c->n_layers; L++)
        if (k3_bind_layer(&st, c, L, &w.lay[L]) != 0) {
            ck(0, "ST bind layer %d", L);
            k3_st_close(&st);
            free(w.lay);
            return;
        }
    if (k3_bind_model(&st, c, 1, &w.mb) != 0) {
        ck(0, "ST model bind");
        k3_st_close(&st);
        free(w.lay);
        return;
    }
    /* resident fp32 expert banks (dequantized MXFP4), one allocation per
     * matrix family kept alive until the binds are freed */
    float **banks = (float **)xmalloc((size_t)3 * c->n_layers * sizeof(float *));
    memset(banks, 0, (size_t)3 * c->n_layers * sizeof(float *));
    for (int L = 0; L < c->n_layers; L++) {
        if (!w.lay[L].lay.moe) continue;
        K3MoeW *moe      = &w.lay[L].moe;
        const size_t p13 = (size_t)c->moe_inter * c->latent;
        const size_t p2  = (size_t)c->latent * c->moe_inter;
        float *b1        = (float *)xmalloc((size_t)c->n_experts * p13 * sizeof(float));
        float *b3        = (float *)xmalloc((size_t)c->n_experts * p13 * sizeof(float));
        float *b2        = (float *)xmalloc((size_t)c->n_experts * p2 * sizeof(float));
        load_st_experts(&st, c, L, b1, b3, b2);
        moe->w1          = b1;
        moe->w3          = b3;
        moe->w2          = b2;
        banks[3 * L]     = b1;
        banks[3 * L + 1] = b3;
        banks[3 * L + 2] = b2;
    }
    run_logits_gate(&w, c, ids, T, ref, "ST vs ref_logits.json", scratch, h, br, kstate,
                    lg);
    for (int L = 0; L < c->n_layers; L++) {
        free(banks[3 * L]);
        free(banks[3 * L + 1]);
        free(banks[3 * L + 2]);
        k3_bind_free(&w.lay[L]);
    }
    free(banks);
    free(w.lay);
    k3_bind_model_free(&w.mb);
    k3_st_close(&st);
}

/* the GGUF full-model gate (single + multi): k3_gguf_bind + expert source */
static void run_gguf_forward_gate(const K3Cfg *c, const int *ids, int T, const Ref *ref,
                                  const char *tag, float *scratch, float *h, float *br,
                                  float *kstate, float *lg, K3Gguf *g, K3GgufBind *bind)
{
    K3GgufExpertSrc es;
    if (k3_gguf_expert_src_init(&es, g, c, (int64_t)1 << 26) != 0) {
        ck(0, "%s: expert source init", tag);
        return;
    }
    Fwd w;
    memset(&w, 0, sizeof w);
    w.n_bound = c->n_layers;
    w.exp_src = &es.src;
    w.gguf    = bind;
    w.lay     = (K3LayerBind *)xmalloc((size_t)c->n_layers * sizeof(K3LayerBind));
    if (k3_gguf_bind_model(bind, 1, &w.mb) != 0) {
        ck(0, "%s: model bind", tag);
        k3_gguf_expert_src_free(&es);
        free(w.lay);
        return;
    }
    run_logits_gate(&w, c, ids, T, ref, tag, scratch, h, br, kstate, lg);
    k3_gguf_expert_src_free(&es);
    k3_bind_model_free(&w.mb);
    free(w.lay);
}

/* --------------------------------------------------------- bf16eq finder */
/* The BIT-EXACT SUB-GATE's bind path. The map's contract table demands Q8_0 for
 * trunk rows, so the F32-trunk variant cannot go through k3_gguf_bind_layer;
 * this finder feeds the SAME plan (k3_bind_layer_mem) with the same
 * transformations (F32 -> bf16 RNE, composite kv_b, A_log pad, const-ones) over
 * the bf16trunk fixture's bytes. Everything else in the path is the engine's. */
typedef struct {
    const K3Gguf *g;
    const K3Cfg *c;
    int layer; /* -1 = model level (manual, not used here) */
    unsigned char *scratch;
    size_t used, cap;
    float *ones;
} Bf16Ctx;

static size_t al8(size_t x)
{
    return (x + 7u) & ~(size_t)7u;
}

static int is_reqw_name(const char *name)
{
    static const char *const tails[] = {
        "input_layernorm.weight",
        "post_attention_layernorm.weight",
        "self_attention_res_norm.weight",
        "self_attention_res_proj.weight",
        "mlp_res_norm.weight",
        "mlp_res_proj.weight",
        "self_attn.q_a_layernorm.weight",
        "self_attn.kv_a_layernorm.weight",
        "self_attn.A_log",
        "self_attn.dt_bias",
        "self_attn.o_norm.weight",
        "self_attn.q_conv1d.weight",
        "self_attn.k_conv1d.weight",
        "self_attn.v_conv1d.weight",
        "block_sparse_moe.gate.weight",
        "block_sparse_moe.gate.e_score_correction_bias",
        "block_sparse_moe.routed_expert_norm.weight",
        "model.norm.weight",
        "model.output_attn_res_norm.weight",
        "model.output_attn_res_proj.weight",
    };
    for (size_t i = 0; i < sizeof tails / sizeof *tails; i++)
        if (strstr(name, tails[i])) return 1;
    return 0;
}

static int bf16eq_find(void *ctx, const char *name, int64_t *off, int64_t *nbytes,
                       int *dtype)
{
    Bf16Ctx *b = (Bf16Ctx *)ctx;
    char gname[160];
    if (k3_gguf_map_translate(b->c, b->layer, name, gname, sizeof gname) != 0) return -1;
    if (!strcmp(gname, "(const ones)")) {
        size_t o = al8(b->used);
        if (o + (size_t)b->c->hidden * 4 > b->cap) return -1;
        memcpy(b->scratch + o, b->ones, (size_t)b->c->hidden * 4);
        b->used = o + (size_t)b->c->hidden * 4;
        *off    = (int64_t)o;
        *nbytes = (int64_t)b->c->hidden * 4;
        *dtype  = K3_DT_F32;
        return 0;
    }
    if (!strcmp(gname, "(composite kv_b)")) {
        char kb[96], vb[96];
        snprintf(kb, sizeof kb, "blk.%d.attn_k_b.weight", b->layer);
        snprintf(vb, sizeof vb, "blk.%d.attn_v_b.weight", b->layer);
        const K3Tensor *kt = k3_gguf_find(b->g, kb);
        const K3Tensor *vt = k3_gguf_find(b->g, vb);
        if (!kt || !vt) return -1;
        const int64_t QN = b->c->qk_nope, VH = b->c->v_head, KL = b->c->kv_lora,
                      H = b->c->n_heads;
        static unsigned char raw[1 << 20];
        static uint16_t bf16[1 << 18];
        if (k3_gguf_read(b->g, kt, raw) != kt->nbytes ||
            k3_gguf_read(b->g, vt, raw + kt->nbytes) != vt->nbytes)
            return -1;
        K3GgufTensor kg, vg;
        K3GgufExpect ex;
        memset(&kg, 0, sizeof kg);
        kg.ggml_type = K3_GGUF_TYPE_F32;
        kg.ndim      = 3;
        kg.ne[0]     = QN;
        kg.ne[1]     = KL;
        kg.ne[2]     = H;
        kg.nbytes    = kt->nbytes;
        kg.data      = raw;
        memset(&ex, 0, sizeof ex);
        ex.ndim  = 3;
        ex.ne[0] = QN;
        ex.ne[1] = KL;
        ex.ne[2] = H;
        if (k3_gguf_dequant(&kg, K3_GGUF_DEQ_BF16, bf16, &ex) != 0) return -1;
        const uint16_t *ks = bf16;
        memset(&vg, 0, sizeof vg);
        vg.ggml_type = K3_GGUF_TYPE_F32;
        vg.ndim      = 3;
        vg.ne[0]     = KL;
        vg.ne[1]     = VH;
        vg.ne[2]     = H;
        vg.nbytes    = vt->nbytes;
        vg.data      = raw + kt->nbytes;
        memset(&ex, 0, sizeof ex);
        ex.ndim  = 3;
        ex.ne[0] = KL;
        ex.ne[1] = VH;
        ex.ne[2] = H;
        if (k3_gguf_dequant(&vg, K3_GGUF_DEQ_BF16, bf16 + H * KL * QN, &ex) != 0)
            return -1;
        const uint16_t *vs      = bf16 + H * KL * QN;
        const int64_t out_bytes = H * (QN + VH) * KL * 2;
        size_t o                = al8(b->used);
        if (o + (size_t)out_bytes > b->cap) return -1;
        uint16_t *dst = (uint16_t *)(b->scratch + o);
        for (int64_t h = 0; h < H; h++) {
            for (int64_t i = 0; i < QN; i++)
                for (int64_t j = 0; j < KL; j++)
                    dst[(size_t)(h * (QN + VH) + i) * KL + j] =
                        ks[(size_t)(h * KL + j) * QN + i];
            for (int64_t i = 0; i < VH; i++)
                memcpy(dst + (size_t)(h * (QN + VH) + QN + i) * KL,
                       vs + (size_t)(h * VH + i) * KL, (size_t)KL * 2);
        }
        b->used = o + (size_t)out_bytes;
        *off    = (int64_t)o;
        *nbytes = out_bytes;
        *dtype  = K3_DT_BF16;
        return 0;
    }
    const K3Tensor *t = k3_gguf_find(b->g, gname);
    if (!t) return -1;
    if (b->g->gtype[t - b->g->t] != K3_GGUF_TYPE_F32) return -1; /* the variant */
    static unsigned char raw[1 << 20];
    if (k3_gguf_read(b->g, t, raw) != t->nbytes) return -1;

    const int reqw    = is_reqw_name(name);
    const int is_alog = strstr(name, ".self_attn.A_log") != NULL;
    int64_t out_numel = 1;
    for (int d = 0; d < t->ndim; d++) out_numel *= t->shape[d];
    int64_t out_bytes;
    int dt;
    if (is_alog) {
        /* engine plan: want kda_head_dim, take kda_heads; the file ships
         * kda_heads; pad the tail exactly like the map's MF_PAD_D */
        out_numel = b->c->kda_head_dim;
        out_bytes = out_numel * 4;
        dt        = K3_DT_F32;
    } else if (reqw) {
        out_bytes = out_numel * 4;
        dt        = K3_DT_F32;
    } else {
        out_bytes = out_numel * 2;
        dt        = K3_DT_BF16;
    }
    size_t o = al8(b->used);
    if (o + (size_t)out_bytes > b->cap) return -1;
    unsigned char *dst = b->scratch + o;
    K3GgufTensor gt;
    K3GgufExpect ex;
    memset(&gt, 0, sizeof gt);
    gt.ggml_type = K3_GGUF_TYPE_F32;
    gt.ndim      = t->ndim;
    for (int d = 0; d < t->ndim; d++) gt.ne[d] = t->shape[d];
    gt.nbytes = t->nbytes;
    gt.data   = raw;
    memset(&ex, 0, sizeof ex);
    ex.ndim = t->ndim;
    for (int d = 0; d < t->ndim; d++) ex.ne[d] = t->shape[d];
    if (k3_gguf_dequant(&gt, reqw ? K3_GGUF_DEQ_F32 : K3_GGUF_DEQ_BF16, dst, &ex) != 0)
        return -1;
    if (is_alog) {
        memset(dst + 4 * (size_t)t->shape[0], 0,
               4 * (size_t)(b->c->kda_head_dim - t->shape[0]));
    }
    b->used = o + (size_t)out_bytes;
    *off    = (int64_t)o;
    *nbytes = out_bytes;
    *dtype  = dt;
    return 0;
}

/* the bf16trunk full-model gate: k3_bind_layer_mem + the bf16eq finder */
static void run_bf16trunk_forward_gate(const char *gg_dir, const K3Cfg *c, const int *ids,
                                       int T, const Ref *ref, float *scratch, float *h,
                                       float *br, float *kstate, float *lg)
{
    printf("== full-model gate: bf16trunk variant (bit-exact sub-gate) ==\n");
    K3Gguf g;
    if (k3_gguf_open(&g, gg_dir) != 0) {
        ck(0, "open the bf16trunk fixture");
        return;
    }
    K3GgufExpertSrc es;
    if (k3_gguf_expert_src_init(&es, &g, c, (int64_t)1 << 26) != 0) {
        ck(0, "bf16trunk: expert source init");
        k3_gguf_close(&g);
        return;
    }
    Bf16Ctx ctx;
    memset(&ctx, 0, sizeof ctx);
    ctx.g = &g;
    ctx.c = c;
    /* one region per layer: the binds' pointers must stay valid through the
     * whole forward (the map path achieves this by refilling per token; here
     * the dequantized bytes are simply all resident) */
    ctx.cap     = (size_t)c->n_layers * (2u << 20);
    ctx.scratch = (unsigned char *)xmalloc(ctx.cap);
    ctx.ones    = (float *)xmalloc((size_t)c->hidden * sizeof(float));
    for (int i = 0; i < c->hidden; i++) ctx.ones[i] = 1.0f;

    Fwd w;
    memset(&w, 0, sizeof w);
    w.n_bound = c->n_layers;
    w.exp_src = &es.src;
    w.lay     = (K3LayerBind *)xmalloc((size_t)c->n_layers * sizeof(K3LayerBind));
    unsigned char *widen = (unsigned char *)xmalloc(k3_bind_widen_bytes(c));
    K3MemSrc src;
    src.find = bf16eq_find;
    src.ctx  = &ctx;
    for (int L = 0; L < c->n_layers; L++) {
        ctx.layer = L;
        ctx.used  = (size_t)L * (2u << 20);
        size_t wu = 0;
        if (k3_bind_layer_mem(c, L, &w.lay[L], ctx.scratch, &src, widen,
                              k3_bind_widen_bytes(c), &wu) != 0) {
            ck(0, "bf16trunk: bind layer %d", L);
            k3_gguf_expert_src_free(&es);
            k3_gguf_close(&g);
            return;
        }
    }
    /* model level: manual (embed/lm_head F32->bf16, norm/res folds F32) */
    {
        static unsigned char raw[1 << 20];
        const K3Tensor *t;
        const int64_t nemb = (int64_t)c->vocab * c->hidden;
        memset(&w.mb, 0, sizeof w.mb);
        w.mb.blob        = xmalloc((size_t)(2 * nemb * 2 + 4 * c->hidden * 4) + 64);
        unsigned char *p = (unsigned char *)w.mb.blob;
        uint16_t *emb    = (uint16_t *)p;
        uint16_t *lhh    = (uint16_t *)(p + (size_t)nemb * 2);
        float *norm      = (float *)(p + (size_t)2 * nemb * 2);
        float *rn        = norm + c->hidden;
        float *rp        = rn + c->hidden;
        t                = k3_gguf_find(&g, "token_embd.weight");
        if (!t || k3_gguf_read(&g, t, raw) != t->nbytes) {
            ck(0, "bf16trunk: read token_embd");
            return;
        }
        K3GgufTensor gt;
        K3GgufExpect ex;
        memset(&gt, 0, sizeof gt);
        gt.ggml_type = K3_GGUF_TYPE_F32;
        gt.ndim      = 2;
        gt.ne[0]     = c->hidden;
        gt.ne[1]     = c->vocab;
        gt.nbytes    = t->nbytes;
        gt.data      = raw;
        memset(&ex, 0, sizeof ex);
        ex.ndim  = 2;
        ex.ne[0] = c->hidden;
        ex.ne[1] = c->vocab;
        if (k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, emb, &ex) != 0) {
            ck(0, "bf16trunk: dequant embed");
            return;
        }
        t = k3_gguf_find(&g, "output.weight");
        if (!t || k3_gguf_read(&g, t, raw) != t->nbytes) {
            ck(0, "bf16trunk: read output");
            return;
        }
        gt.ne[0]  = c->hidden;
        gt.ne[1]  = c->vocab;
        gt.nbytes = t->nbytes;
        if (k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, lhh, &ex) != 0) {
            ck(0, "bf16trunk: dequant lm_head");
            return;
        }
        t = k3_gguf_find(&g, "output_norm.weight");
        if (!t || k3_gguf_read(&g, t, raw) != t->nbytes) {
            ck(0, "bf16trunk: read output_norm");
            return;
        }
        memcpy(norm, raw, (size_t)t->nbytes);
        t = k3_gguf_find(&g, "output_res_score.weight");
        if (!t || k3_gguf_read(&g, t, raw) != t->nbytes) {
            ck(0, "bf16trunk: read output_res_score");
            return;
        }
        memcpy(rn, raw, (size_t)t->nbytes);
        for (int i = 0; i < c->hidden; i++) rp[i] = 1.0f;
        w.mb.embed        = emb;
        w.mb.lm_head      = lhh;
        w.mb.norm         = norm;
        w.mb.out_res_norm = rn;
        w.mb.out_res_proj = rp;
        w.mb.wdt          = K3_WBF16;
    }
    run_logits_gate(&w, c, ids, T, ref, "bf16trunk vs its reference", scratch, h, br,
                    kstate, lg);
    for (int L = 0; L < c->n_layers; L++) k3_bind_free(&w.lay[L]);
    free(w.lay);
    free(widen);
    free(ctx.scratch);
    free(ctx.ones);
    k3_bind_model_free(&w.mb);
    k3_gguf_expert_src_free(&es);
    k3_gguf_close(&g);
}

/* ------------------------------------------------------------------ main */
int main(int argc, char **argv)
{
    const char *fx = argc > 1 ? argv[1] : "tests/fixtures";
    char st_dir[512], gg_dir[512], gm_dir[512], bt_dir[512], g2_path[512];
    snprintf(st_dir, sizeof st_dir, "%s/tiny_st", fx);
    snprintf(gg_dir, sizeof gg_dir, "%s/tiny_gguf", fx);
    snprintf(gm_dir, sizeof gm_dir, "%s/tiny_gguf_multi", fx);
    snprintf(bt_dir, sizeof bt_dir, "%s/tiny_gguf_bf16trunk", fx);
    snprintf(g2_path, sizeof g2_path, "%s/gguf_gate2_golden.bin", fx);

    open_fixture(gg_dir, 1, 353, 0, "tiny_gguf (single shard)");
    open_fixture(gm_dir, 3, 353, 0, "tiny_gguf_multi (3 shards)");
    open_fixture(bt_dir, 1, 353, 1, "tiny_gguf_bf16trunk (F32 trunk)");

    run_bit_exact_trunk(st_dir, bt_dir);

    run_gate2(gg_dir, g2_path);

    /* ---- full-model gates ---- */
    K3Gguf g;
    if (k3_gguf_open(&g, gg_dir) != 0) {
        ck(0, "open the gguf fixture for the forward gates");
        return 1;
    }
    K3Cfg c;
    static int fa[64];
    if (!k3_gguf_cfg(&g, &c, fa, 64)) {
        ck(0, "forward gates config");
        k3_gguf_close(&g);
        return 1;
    }

    const int ids[5]  = {3, 7, 11, 5, 9};
    const int T       = 5;
    const int maxb    = c.n_layers / c.attn_res_block + 2;
    const int P       = c.kda_heads * c.kda_head_dim;
    const size_t kper = (size_t)P * c.kda_head_dim + (size_t)3 * P * (c.conv_k - 1);
    size_t need       = k3_layer_scratch(&c, T);
    size_t alt        = (size_t)(maxb + 2) * (size_t)c.hidden + (size_t)c.vocab;
    if (alt > need) need = alt;
    float *scratch = (float *)xmalloc(need * sizeof(float));
    float *h       = (float *)xmalloc((size_t)T * c.hidden * sizeof(float));
    float *br    = (float *)xmalloc((size_t)T * (size_t)maxb * c.hidden * sizeof(float));
    float *ks    = (float *)xmalloc(kper * (size_t)c.n_layers * sizeof(float));
    float *lg_st = (float *)xmalloc((size_t)c.vocab * sizeof(float));
    float *lg_gg = (float *)xmalloc((size_t)c.vocab * sizeof(float));
    float *lg_sm = (float *)xmalloc((size_t)c.vocab * sizeof(float));
    float *lg_bt = (float *)xmalloc((size_t)c.vocab * sizeof(float));

    Ref ref_st, ref_sg, ref_sm, ref_bt;
    snprintf(ref_st.path, sizeof ref_st.path, "%s/ref_logits.json", st_dir);
    snprintf(ref_sg.path, sizeof ref_sg.path, "%s/ref_logits_gguf.json", gg_dir);
    snprintf(ref_sm.path, sizeof ref_sm.path, "%s/ref_logits_gguf.json", gm_dir);
    snprintf(ref_bt.path, sizeof ref_bt.path, "%s/ref_logits_gguf.json", bt_dir);

    run_st_forward_gate(st_dir, &c, ids, T, &ref_st, scratch, h, br, ks, lg_st);

    K3GgufBind bind;
    if (k3_gguf_bind_init(&bind, &g, &c) != 0 ||
        k3_gguf_bind_alloc(&bind, c.n_layers, (int64_t)1 << 26) != 0) {
        ck(0, "gguf bind alloc");
        k3_gguf_close(&g);
        return 1;
    }
    run_gguf_forward_gate(&c, ids, T, &ref_sg, "single vs its ref", scratch, h, br, ks,
                          lg_gg, &g, &bind);

    K3Gguf gm;
    if (k3_gguf_open(&gm, gm_dir) != 0) {
        ck(0, "open the multi-shard fixture");
        return 1;
    }
    K3GgufBind bindm;
    if (k3_gguf_bind_init(&bindm, &gm, &c) != 0 ||
        k3_gguf_bind_alloc(&bindm, c.n_layers, (int64_t)1 << 26) != 0) {
        ck(0, "multi bind alloc");
        k3_gguf_close(&gm);
        return 1;
    }
    run_gguf_forward_gate(&c, ids, T, &ref_sm, "multi vs its ref", scratch, h, br, ks,
                          lg_sm, &gm, &bindm);
    ck(memcmp(lg_gg, lg_sm, (size_t)c.vocab * sizeof(float)) == 0,
       "single-shard and multi-shard forwards are BIT-IDENTICAL");
    k3_gguf_bind_free(&bindm);
    k3_gguf_close(&gm);
    k3_gguf_bind_free(&bind);
    k3_gguf_close(&g);

    /* the sub-gate's logits leg: bf16trunk vs the ST run - the trunks are
     * bit-identical (proved above), so any difference is the expert
     * encodings ONLY (Gate-2 class) */
    run_bf16trunk_forward_gate(bt_dir, &c, ids, T, &ref_bt, scratch, h, br, ks, lg_bt);
    {
        const double d = rel_l2(lg_bt, lg_st, c.vocab);
        printf("  bf16trunk vs ST logits (expert-only): rel-L2 %.4f "
               "(bound 0.5)\n",
               d);
        ck(d <= 0.5, "bit-exact sub-gate: expert-only difference within 2x "
                     "the measured 0.19 class");
    }

    free(scratch);
    free(h);
    free(br);
    free(ks);
    free(lg_st);
    free(lg_gg);
    free(lg_sm);
    free(lg_bt);

    printf("\n%s (%d failures)\n",
           fails == 0 ? "GGUF PARITY GATES PASSED" : "GGUF PARITY GATES FAILED", fails);
    return fails == 0 ? 0 : 1;
}
