/* test_gguf_dequant.c - dequant kernels against committed golden values.
 *
 * The golden file (tests/fixtures/gguf_dequant_golden.bin, generated by
 * tools/emit_gguf_dequant_golden.py) carries raw quantized blocks - REAL bytes
 * from the 554 GB Kimi-K3-UD-IQ1_S file plus deterministic synthetic blocks -
 * and the expected fp32 and bf16 dequant outputs computed by an independent
 * numpy reference. The dequant math is a handful of exactly-representable fp32
 * operations, so the comparison is BIT-EXACT, not tolerance-based.
 *
 * The negative half of the contract (D4) is exercised here too, in code: wrong
 * dims, wrong nbytes, unknown types, negative dims, int64 overflow in the nbytes
 * formula, missing shape expectation, expert slices out of range. Every one of
 * those must fail loud (return -1), never wrap or silently succeed.
 *
 * usage: test_gguf_dequant <golden.bin>
 */
#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "k3_gguf_dequant.h"

static int nfail;

static void fail(const char *fmt, ...)
{
    va_list ap;
    nfail++;
    fprintf(stderr, "  FAIL: ");
    va_start(ap, fmt);
    vfprintf(stderr, fmt, ap);
    va_end(ap);
    fputc('\n', stderr);
}

static const char *type_name(int t)
{
    switch (t) {
    case K3_GGUF_TYPE_F32:   return "F32";
    case K3_GGUF_TYPE_Q8_0:  return "Q8_0";
    case K3_GGUF_TYPE_IQ1_S: return "IQ1_S";
    default:                 return "?";
    }
}

static uint32_t rd32(const uint8_t *p)
{
    return (uint32_t)p[0] | (uint32_t)p[1] << 8 | (uint32_t)p[2] << 16 |
           (uint32_t)p[3] << 24;
}

static uint64_t rd64(const uint8_t *p)
{
    return (uint64_t)rd32(p) | (uint64_t)rd32(p + 4) << 32;
}

/* One golden case, as a pointer into the loaded file. */
typedef struct {
    int       type, ndim;
    int64_t   ne[4];
    uint64_t  nraw, nvals;
    uint32_t  flags;
    const uint8_t *raw, *f32, *bf16;
} GoldenCase;

/* Validate the header of an in-memory golden buffer. Split out of load_golden so
 * the harness's own failure paths (bad magic/version, truncation) are testable. */
static int parse_golden(const uint8_t *buf, size_t len, int *ncases)
{
    if (len < 12) {
        fprintf(stderr, "golden: file too small (%zu bytes)\n", len);
        return -1;
    }
    if (memcmp(buf, "K3DG", 4) != 0) {
        fprintf(stderr, "golden: bad magic\n");
        return -1;
    }
    if (rd32(buf + 4) != 1) {
        fprintf(stderr, "golden: unsupported version %u\n", rd32(buf + 4));
        return -1;
    }
    *ncases = (int)rd32(buf + 8);
    return 0;
}

static int load_golden(const char *path, uint8_t **buf, size_t *len, int *ncases)
{
    FILE *f = fopen(path, "rb");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); return -1; }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz < 12) { fclose(f); fprintf(stderr, "%s too small\n", path); return -1; }
    uint8_t *b = (uint8_t *)malloc((size_t)sz);
    if (!b) { fclose(f); fprintf(stderr, "alloc failed\n"); return -1; }
    if (fread(b, 1, (size_t)sz, f) != (size_t)sz) {
        fclose(f); free(b); fprintf(stderr, "short read on %s\n", path); return -1;
    }
    fclose(f);
    if (parse_golden(b, (size_t)sz, ncases) != 0) { free(b); return -1; }
    *buf = b; *len = (size_t)sz;
    return 0;
}

/* Parse case i, bounds-checked against the buffer end; returns NULL on a
 * truncated record (the caller reports it). nraw/nvals are untrusted u64s from
 * the file, so every advance is verified before it happens. */
static const uint8_t *parse_case(const uint8_t *p, const uint8_t *end, GoldenCase *c)
{
    if ((size_t)(end - p) < 64) return NULL;
    c->type = (int)rd32(p); c->ndim = (int)rd32(p + 4); p += 8;
    for (int i = 0; i < 4; i++) { c->ne[i] = (int64_t)rd64(p); p += 8; }
    c->nraw = rd64(p); c->nvals = rd64(p + 8);
    c->flags = rd32(p + 16); p += 24;
    if (c->nraw > (uint64_t)(end - p)) return NULL;
    c->raw = p; p += c->nraw;
    if (c->nvals > (uint64_t)(end - p) / 4) return NULL;
    c->f32 = p; p += c->nvals * 4;
    if (c->nvals > (uint64_t)(end - p) / 2) return NULL;
    c->bf16 = p; p += c->nvals * 2;
    return p;
}

/* ----------------------------------------------------------------- cases ---- */
static void run_golden_case(int idx, const GoldenCase *c)
{
    printf("  case %2d: %-4s ne=[%lld %lld %lld %lld] %llu vals%s\n",
           idx, type_name(c->type), (long long)c->ne[0], (long long)c->ne[1],
           (long long)c->ne[2], (long long)c->ne[3],
           (unsigned long long)c->nvals,
           (c->flags & 2) ? " (+expert slices)" : "");

    K3GgufTensor t;
    memset(&t, 0, sizeof t);
    t.ggml_type = c->type;
    t.ndim = c->ndim;
    for (int i = 0; i < 4; i++) t.ne[i] = c->ne[i];
    t.nbytes = (int64_t)c->nraw;
    t.data = c->raw;

    K3GgufExpect ex;
    memset(&ex, 0, sizeof ex);
    ex.ndim = c->ndim;
    for (int i = 0; i < 4; i++) ex.ne[i] = c->ne[i];

    /* the nbytes formula must reproduce the file's byte count exactly */
    int64_t nb = k3_gguf_dequant_nbytes(c->type, c->ndim, c->ne);
    if (nb != (int64_t)c->nraw)
        fail("case %d: nbytes formula gave %lld, file says %llu",
             idx, (long long)nb, (unsigned long long)c->nraw);

    size_t nvals = (size_t)c->nvals;
    float *f32 = nvals ? (float *)malloc(nvals * sizeof(float)) : NULL;
    uint16_t *bf16 = nvals ? (uint16_t *)malloc(nvals * sizeof(uint16_t)) : NULL;

    if (k3_gguf_dequant(&t, K3_GGUF_DEQ_F32, f32, &ex) != 0)
        fail("case %d: fp32 dequant returned error", idx);
    else if (nvals && memcmp(f32, c->f32, nvals * sizeof(float)) != 0) {
        for (size_t i = 0; i < nvals; i++) {
            union { float f; uint32_t u; } a, b;
            memcpy(&a, &f32[i], 4);          /* c->f32 may be unaligned; memcpy only */
            memcpy(&b, c->f32 + 4 * i, 4);
            if (a.u != b.u) {
                fail("case %d: fp32 mismatch at %zu: got bits %08x (%g), want %08x (%g)",
                     idx, i, a.u, (double)a.f, b.u, (double)b.f);
                break;
            }
        }
    }

    if (k3_gguf_dequant(&t, K3_GGUF_DEQ_BF16, bf16, &ex) != 0)
        fail("case %d: bf16 dequant returned error", idx);
    else if (!(c->flags & 1) && nvals)
        fail("case %d: fixture carries no bf16 block (flags bit0 clear)", idx);
    else if ((c->flags & 1) && nvals &&
             memcmp(bf16, c->bf16, nvals * sizeof(uint16_t)) != 0) {
        for (size_t i = 0; i < nvals; i++) {
            uint16_t a, b;
            memcpy(&a, &bf16[i], 2);         /* c->bf16 may be unaligned; memcpy only */
            memcpy(&b, c->bf16 + 2 * i, 2);
            if (a != b) {
                fail("case %d: bf16 mismatch at %zu: got %04x want %04x",
                     idx, i, a, b);
                break;
            }
        }
    }

    /* 3-D IQ1_S slice case: dequant each expert's contiguous slice and compare
     * against the corresponding half of the full-tensor expectation. */
    if (c->flags & 2) {
        int64_t slice_vals = ((c->ne[0] + K3_GGUF_IQ1_S_QK - 1) / K3_GGUF_IQ1_S_QK) *
                             K3_GGUF_IQ1_S_QK * c->ne[1];
        for (int64_t e = 0; e < c->ne[2]; e++) {
            if (k3_gguf_dequant_expert_slice(&t, e, K3_GGUF_DEQ_F32, f32, &ex) != 0) {
                fail("case %d: expert slice %lld returned error", idx, (long long)e);
                continue;
            }
            const float *want = (const float *)c->f32 + e * slice_vals;
            if (memcmp(f32, want, (size_t)slice_vals * sizeof(float)) != 0)
                fail("case %d: expert slice %lld differs from full-tensor half",
                     idx, (long long)e);
        }
    }

    free(f32);
    free(bf16);
}

/* ------------------------------------------------------------ negative ---- */
static void expect_fail(const char *what, int rc)
{
    if (rc == 0) fail("%s: expected a loud failure, got success", what);
    else printf("  neg: %-46s correctly rejected\n", what);
}

static void run_negative_tests(void)
{
    printf("  negative contract tests\n");

    K3GgufTensor t;
    memset(&t, 0, sizeof t);
    t.ggml_type = K3_GGUF_TYPE_Q8_0;
    t.ndim = 2;
    t.ne[0] = 64; t.ne[1] = 2;
    t.nbytes = 2 * 2 * K3_GGUF_Q8_0_BSZ;    /* 2 rows x 2 blocks */
    uint8_t raw[4 * K3_GGUF_Q8_0_BSZ];
    memset(raw, 0x7f, sizeof raw);
    t.data = raw;

    K3GgufExpect ex;
    memset(&ex, 0, sizeof ex);
    ex.ndim = 2;
    ex.ne[0] = 64; ex.ne[1] = 2;
    float out[128];

    /* unknown type: dispatch must fail loud, never decode as something else */
    K3GgufTensor bad = t;
    bad.ggml_type = 42;
    expect_fail("unknown ggml_type 42 (dequant)", k3_gguf_dequant(&bad, K3_GGUF_DEQ_F32, out, &ex));
    int64_t ne42[4] = { 64, 2, 1, 1 };
    expect_fail("unknown ggml_type 42 (nbytes)", k3_gguf_dequant_nbytes(42, 2, ne42) < 0 ? 1 : 0);

    /* shape contract: NULL expectation is not allowed */
    expect_fail("NULL shape expectation", k3_gguf_dequant(&t, K3_GGUF_DEQ_F32, out, NULL));

    /* wrong dims, one by one */
    for (int d = 0; d < 2; d++) {
        K3GgufExpect we = ex;
        we.ne[d]++;
        expect_fail("wrong expected ne (dequant)", k3_gguf_dequant(&t, K3_GGUF_DEQ_F32, out, &we));
    }
    K3GgufExpect we2 = ex;
    we2.ndim = 3;
    expect_fail("wrong expected ndim", k3_gguf_dequant(&t, K3_GGUF_DEQ_F32, out, &we2));

    /* nbytes must equal the block formula */
    bad = t;
    bad.nbytes = t.nbytes + 1;
    expect_fail("nbytes off by one", k3_gguf_dequant(&bad, K3_GGUF_DEQ_F32, out, &ex));

    /* negative dims */
    bad = t;
    bad.ne[0] = -4;
    expect_fail("negative dim", k3_gguf_dequant(&bad, K3_GGUF_DEQ_F32, out, &ex));

    /* NULL data with nbytes > 0 */
    bad = t;
    bad.data = NULL;
    expect_fail("NULL data with nbytes > 0", k3_gguf_dequant(&bad, K3_GGUF_DEQ_F32, out, &ex));

    /* NULL dst for a non-empty tensor */
    expect_fail("NULL dst", k3_gguf_dequant(&t, K3_GGUF_DEQ_F32, NULL, &ex));

    /* giant shapes: nbytes must fail loud, not wrap */
    int64_t big1[4] = { INT64_MAX, 1, 1, 1 };
    expect_fail("Q8_0 nbytes overflow (ne0=INT64_MAX)", k3_gguf_dequant_nbytes(K3_GGUF_TYPE_Q8_0, 1, big1) < 0 ? 1 : 0);
    int64_t big2[4] = { INT64_MAX, 2, 1, 1 };
    expect_fail("F32 nbytes overflow (ne0=INT64_MAX)", k3_gguf_dequant_nbytes(K3_GGUF_TYPE_F32, 2, big2) < 0 ? 1 : 0);
    /* IQ1_S nbytes fits (5x smaller per value) but the padded VALUE count does not */
    int64_t nb_big = k3_gguf_dequant_nbytes(K3_GGUF_TYPE_IQ1_S, 1, big1);
    if (nb_big <= 0)
        fail("IQ1_S ne0=INT64_MAX: expected nbytes to FIT (got %lld)", (long long)nb_big);
    else {
        K3GgufTensor big = t;
        big.ggml_type = K3_GGUF_TYPE_IQ1_S;
        big.ndim = 1;
        big.ne[0] = INT64_MAX;
        big.nbytes = nb_big;
        big.data = raw;                     /* never dereferenced: fails on count */
        K3GgufExpect bigex;
        memset(&bigex, 0, sizeof bigex);
        bigex.ndim = 1;
        bigex.ne[0] = INT64_MAX;
        expect_fail("IQ1_S value-count overflow",
                    k3_gguf_dequant(&big, K3_GGUF_DEQ_F32, out, &bigex));
    }

    /* expert slices: wrong tensor shape/type/expert index must fail */
    K3GgufTensor iq;
    memset(&iq, 0, sizeof iq);
    iq.ggml_type = K3_GGUF_TYPE_IQ1_S;
    iq.ndim = 3;
    iq.ne[0] = 512; iq.ne[1] = 1; iq.ne[2] = 2;
    iq.nbytes = 4 * K3_GGUF_IQ1_S_BSZ;
    uint8_t iqraw[4 * K3_GGUF_IQ1_S_BSZ];
    memset(iqraw, 0xaa, sizeof iqraw);
    iq.data = iqraw;
    K3GgufExpect iqe;
    memset(&iqe, 0, sizeof iqe);
    iqe.ndim = 3;
    iqe.ne[0] = 512; iqe.ne[1] = 1; iqe.ne[2] = 2;

    expect_fail("expert slice out of range (e=2 of 2)",
                k3_gguf_dequant_expert_slice(&iq, 2, K3_GGUF_DEQ_F32, out, &iqe));
    expect_fail("expert slice negative index",
                k3_gguf_dequant_expert_slice(&iq, -1, K3_GGUF_DEQ_F32, out, &iqe));
    K3GgufTensor not3d = iq;
    not3d.ndim = 2;
    expect_fail("expert slice on 2-D tensor",
                k3_gguf_dequant_expert_slice(&not3d, 0, K3_GGUF_DEQ_F32, out, &iqe));
    K3GgufTensor notiq = iq;
    notiq.ggml_type = K3_GGUF_TYPE_Q8_0;
    notiq.nbytes = 16 * K3_GGUF_Q8_0_BSZ * 1 * 2;   /* Q8_0 formula for 512x1x2 */
    expect_fail("expert slice on Q8_0 tensor",
                k3_gguf_dequant_expert_slice(&notiq, 0, K3_GGUF_DEQ_F32, out, &iqe));

    /* empty tensors: succeed, write nothing, dst may be NULL */
    K3GgufTensor empty;
    memset(&empty, 0, sizeof empty);
    empty.ggml_type = K3_GGUF_TYPE_F32;
    empty.ndim = 2;
    empty.ne[0] = 0; empty.ne[1] = 5;
    K3GgufExpect em;
    memset(&em, 0, sizeof em);
    em.ndim = 2;
    em.ne[0] = 0; em.ne[1] = 5;
    if (k3_gguf_dequant(&empty, K3_GGUF_DEQ_F32, NULL, &em) != 0)
        fail("empty tensor: expected success");
    else
        printf("  neg: empty tensor with NULL dst correctly accepted\n");

    /* invalid output dtype must fail even on an EMPTY tensor: the dtype check
     * precedes the empty early-return, so no silent path exists */
    expect_fail("invalid out dtype on empty tensor",
                k3_gguf_dequant(&empty, (K3GgufDeqOut)99, NULL, &em));
    expect_fail("invalid out dtype on non-empty tensor",
                k3_gguf_dequant(&t, (K3GgufDeqOut)99, out, &ex));

    /* nbytes formula rejects bad ndim and NULL dims */
    int64_t neok[4] = { 64, 2, 1, 1 };
    expect_fail("nbytes ndim=0", k3_gguf_dequant_nbytes(K3_GGUF_TYPE_Q8_0, 0, neok) < 0 ? 1 : 0);
    expect_fail("nbytes ndim=5", k3_gguf_dequant_nbytes(K3_GGUF_TYPE_Q8_0, 5, neok) < 0 ? 1 : 0);
    expect_fail("nbytes NULL dims", k3_gguf_dequant_nbytes(K3_GGUF_TYPE_Q8_0, 2, NULL) < 0 ? 1 : 0);

    /* expert slice: NULL dst on a non-empty tensor must fail loud, not crash */
    expect_fail("expert slice NULL dst",
                k3_gguf_dequant_expert_slice(&iq, 0, K3_GGUF_DEQ_F32, NULL, &iqe));

    /* expert slice on an EMPTY tensor (data NULL, allowed) must succeed without
     * touching dst - and without NULL+0 pointer arithmetic */
    K3GgufTensor iq_empty = iq;
    iq_empty.ne[0] = 0;
    iq_empty.nbytes = 0;
    iq_empty.data = NULL;
    K3GgufExpect iqe_empty = iqe;
    iqe_empty.ne[0] = 0;
    if (k3_gguf_dequant_expert_slice(&iq_empty, 1, K3_GGUF_DEQ_F32, NULL, &iqe_empty) != 0)
        fail("empty expert slice: expected success");
    else
        printf("  neg: empty expert slice with NULL dst correctly accepted\n");
}

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: test_gguf_dequant <golden.bin>\n");
        return 2;
    }

    uint8_t *buf;
    size_t len;
    int ncases;
    if (load_golden(argv[1], &buf, &len, &ncases) != 0) return 1;

    printf("gguf dequant golden: %d cases from %s\n", ncases, argv[1]);
    const uint8_t *p = buf + 12;
    int parse_ok = 1;
    for (int i = 0; i < ncases; i++) {
        GoldenCase c;
        p = parse_case(p, buf + len, &c);
        if (!p) {
            fail("golden case %d: truncated record (corrupt file or stale fixture)", i);
            parse_ok = 0;
            break;
        }
        run_golden_case(i, &c);
    }
    if (parse_ok && p != buf + len)
        fail("golden file has %td trailing bytes", (ptrdiff_t)(buf + len - p));

    /* the harness itself must reject garbage: a regression that accepted any
     * magic/version, or walked past the end of a truncated fixture, would turn
     * every golden failure into a confusing crash instead of a diagnosis */
    printf("  harness self-tests\n");
    int nc = -1;
    uint8_t bad_magic[12] = { 'X', 'X', 'X', 'X', 1, 0, 0, 0, 0, 0, 0, 0 };
    if (parse_golden(bad_magic, sizeof bad_magic, &nc) == 0)
        fail("bad magic accepted");
    else
        printf("  neg: golden bad magic correctly rejected\n");
    uint8_t bad_ver[12];
    memcpy(bad_ver, "K3DG", 4);
    bad_ver[4] = 2;
    if (parse_golden(bad_ver, sizeof bad_ver, &nc) == 0)
        fail("bad version accepted");
    else
        printf("  neg: golden bad version correctly rejected\n");
    if (parse_golden(bad_magic, 8, &nc) == 0)
        fail("too-small golden accepted");
    else
        printf("  neg: golden too-small correctly rejected\n");
    uint8_t trunc[12 + 40];                    /* header claims one case, 40/64 bytes */
    memcpy(trunc, "K3DG", 4);
    trunc[4] = 1; trunc[8] = 1;
    GoldenCase c0;
    if (parse_case(trunc + 12, trunc + sizeof trunc, &c0) != NULL)
        fail("truncated case record accepted");
    else
        printf("  neg: golden truncated case correctly rejected\n");
    uint8_t trunc2[12 + 64];
    memcpy(trunc2, "K3DG", 4);
    trunc2[4] = 1; trunc2[8] = 1;
    memset(trunc2 + 12, 0, 64);                /* nraw=0 nvals=0: parses, then the
                                                  trailing-bytes check owns the rest */
    GoldenCase c1;
    const uint8_t *p1 = parse_case(trunc2 + 12, trunc2 + sizeof trunc2, &c1);
    if (p1 == NULL)
        fail("valid header with nraw=0/nvals=0 rejected");
    else if (p1 != trunc2 + sizeof trunc2)
        fail("case record end misparsed");
    else
        printf("  neg: golden zero-length case correctly parsed\n");

    run_negative_tests();

    free(buf);
    printf("\n%s (%d failures)\n", nfail == 0 ? "DEQUANT TESTS PASSED" : "DEQUANT TESTS FAILED", nfail);
    return nfail == 0 ? 0 : 1;
}
