/* test_gguf_bind.c - the GGUF io-integration unit (D4a name map + shape
 * contracts, D3a streamed layer bind, native IQ1_S expert source).
 *
 * Four parts:
 *   (a) name-map round trips and shape-contract positives/adversarial cases,
 *       pure table mechanics - no files needed;
 *   (b) requant goldens: k3_mxfp4_quant vs tests/fixtures/mxfp4_quant_golden.bin
 *       (generated by tools/emit_mxfp4_quant_golden.py, the numpy reference),
 *       compared BIT-EXACTLY;
 *   (c) a synthetic 3-layer GGUF fixture (dense KDA + KDA MoE + MLA MoE, all
 *       three merged expert tensors): full bind-path exercises - layer bytes,
 *       layer-buffer reuse (no stale pointers across layer boundaries), the
 *       composite kv_b transpose, the folded res_score/ones pairing, A_log
 *       padding, F32->bf16 conversion, model bind, and the expert source's
 *       admit/evict/hit/miss/INFLIGHT behaviour;
 *   (d) the real-file gate: when K3_GGUF_REAL points at the UD-IQ1_S directory
 *       (or the known default exists), validate EVERY one of the 2,573 tensors
 *       against the contract table (headers only, no data reads) and assert the
 *       expert window arithmetic on real dims. Absent -> SKIP, exit 0.
 */
#define _POSIX_C_SOURCE 200809L

#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "k3_gguf.h"
#include "k3_gguf_dequant.h"
#include "k3_gguf_expert.h"
#include "k3_gguf_map.h"
#include "k3_mxfp4_quant.h"
#include "k3_st.h"

/* Fixture vocabulary: 2^20 so the model-level Q8_0 tensors cross the 64 MiB
 * chunk boundary of the finder's chunked dequant (68 B/row * 2^20 = 71.3 MB). */
#define FIX_VOCAB 1048576u

static int fails;

static void ck(int cond, const char *what)
{
    if (cond)
        printf("  ok    %s\n", what);
    else {
        printf("  FAIL  %s\n", what);
        fails++;
    }
}

/* ------------------------------------------------------------------ builder */
/* A minimal GGUF shard builder, mirroring test_gguf.c's. */

typedef struct {
    unsigned char *b;
    size_t n, cap;
} Buf;

typedef struct {
    Buf b;
    uint32_t nkv;
    size_t info_end;
} Shard;

static void bneed(Buf *b, size_t n)
{
    if (b->n + n > b->cap) {
        size_t nc = b->cap ? b->cap : 1 << 16;
        while (b->n + n > nc) nc *= 2;
        b->b   = (unsigned char *)realloc(b->b, nc);
        b->cap = nc;
    }
}

static void bput(Buf *b, const void *p, size_t n)
{
    bneed(b, n);
    memcpy(b->b + b->n, p, n);
    b->n += n;
}

static void bu8(Buf *b, uint8_t v)
{
    bput(b, &v, 1);
}
static void bu16(Buf *b, uint16_t v)
{
    bput(b, &v, 2);
}
static void bu32(Buf *b, uint32_t v)
{
    bput(b, &v, 4);
}
static void bu64(Buf *b, uint64_t v)
{
    bput(b, &v, 8);
}
static void bf32(Buf *b, float v)
{
    bput(b, &v, 4);
}

static void bstr(Buf *b, const char *s)
{
    bu64(b, strlen(s));
    bput(b, s, strlen(s));
}

static void shard_init(Shard *s, uint64_t ntensors)
{
    memset(s, 0, sizeof *s);
    bput(&s->b, "GGUF", 4);
    bu32(&s->b, 3);
    bu64(&s->b, ntensors);
    bu64(&s->b, 0); /* nkv, patched at finish */
}

static void shard_finish(Shard *s)
{
    memcpy(s->b.b + 16, &s->nkv, 8);
    s->info_end = s->b.n;
    while (s->b.n % 32) bu8(&s->b, 0);
}

static void skey(Shard *s, const char *k)
{
    bstr(&s->b, k);
    s->nkv++;
}

static void skv_str(Shard *s, const char *k, const char *v)
{
    skey(s, k);
    bu32(&s->b, 8);
    bstr(&s->b, v);
}

static void skv_u32(Shard *s, const char *k, uint32_t v)
{
    skey(s, k);
    bu32(&s->b, 4);
    bu32(&s->b, v);
}
static void skv_f32(Shard *s, const char *k, float v)
{
    skey(s, k);
    bu32(&s->b, 6);
    bf32(&s->b, v);
}
static void skv_bool(Shard *s, const char *k, uint8_t v)
{
    skey(s, k);
    bu32(&s->b, 7);
    bu8(&s->b, v);
}
static void skv_i32(Shard *s, const char *k, int32_t v)
{
    skey(s, k);
    bu32(&s->b, 5);
    bu32(&s->b, (uint32_t)v);
}
static void skv_u16(Shard *s, const char *k, uint16_t v)
{
    skey(s, k);
    bu32(&s->b, 2);
    bu16(&s->b, v);
}
static void skv_arr_i32(Shard *s, const char *k, const uint32_t *v, uint32_t n)
{
    skey(s, k);
    bu32(&s->b, 9);
    bu32(&s->b, 5);
    bu64(&s->b, n);
    bput(&s->b, v, (size_t)n * 4);
}

/* One registered tensor: infos are emitted at finish; data is appended in order. */
static int reg_seed; /* distinct data pattern per tensor */

typedef struct {
    const char *name;
    uint32_t ndim;
    uint64_t dims[4];
    uint32_t gtype;
    unsigned char *data;
    size_t nbytes;
} Reg;

/* A_log FOLD test vector (architect fix wave): the checkpoint ships
 * ssm_a = -exp(A_log) (unsloth converter fold); these are the KNOWN A_log
 * values whose fold the bind must recover (A_log = ln(-ssm_a), k3_gguf_map.c).
 * The synthetic fixture's ssm_a tensors carry -exp(ALOG_TRUE) so the bind's
 * unfold is checkable against real numbers, not self-consistency. */
static const float ALOG_TRUE[2] = {-0.5f, 0.25f};

static void reg_tensor(Buf *infos, Reg *r, const char *name, uint32_t ndim,
                       const uint64_t *dims, uint32_t gtype)
{
    (void)infos;
    r->name = strdup(name);
    r->ndim = ndim;
    for (uint32_t i = 0; i < ndim; i++) r->dims[i] = dims[i];
    r->gtype = gtype;
    int64_t qk, bsz;
    switch (gtype) {
    case 0:
        qk  = 1;
        bsz = 4;
        break;
    case 8:
        qk  = 32;
        bsz = 34;
        break;
    default:
        qk  = 256;
        bsz = 50;
        break; /* IQ1_S */
    }
    int64_t nb = ((int64_t)dims[0] + qk - 1) / qk * bsz;
    for (uint32_t i = 1; i < ndim; i++) nb *= (int64_t)dims[i];
    r->nbytes = (size_t)nb;
    r->data   = (unsigned char *)calloc(r->nbytes ? r->nbytes : 1, 1);
    /* deterministic per-tensor pattern, distinct across tensors */
    const unsigned seed = (unsigned)(reg_seed++ * 2654435761u);
    for (size_t i = 0; i < r->nbytes; i++)
        r->data[i] = (unsigned char)((i * 131u + seed + 7u) & 0xFFu);
}

/* Emit the tensor infos + data section into the shard. */
static void emit_tensors(Shard *s, Reg *regs, int n)
{
    uint64_t off = 0;
    for (int i = 0; i < n; i++) {
        bstr(&s->b, regs[i].name);
        bu32(&s->b, regs[i].ndim);
        for (uint32_t d = 0; d < regs[i].ndim; d++) bu64(&s->b, regs[i].dims[d]);
        bu32(&s->b, regs[i].gtype);
        bu64(&s->b, off);
        off += (regs[i].nbytes + 31) & ~(size_t)31; /* 32-aligned starts */
    }
    shard_finish(s);
    for (int i = 0; i < n; i++) {
        bput(&s->b, regs[i].data, regs[i].nbytes);
        size_t pad = (32 - regs[i].nbytes % 32) % 32;
        while (pad--) bu8(&s->b, 0);
    }
}

/* The full kimi-k3.* inventory with the synthetic dims. */
enum { CFG_OK = 0, CFG_HCK_BADVAL };

static void cfg_kv(Shard *s, int variant)
{
    static const uint32_t hck[3] = {0, 0, 1};
    skv_str(s, "general.architecture", "kimi-k3");
    skv_u32(s, "kimi-k3.block_count", 3);
    skv_u32(s, "kimi-k3.context_length", 4096);
    skv_u32(s, "kimi-k3.embedding_length", 64);
    skv_u32(s, "kimi-k3.feed_forward_length", 64);
    skv_u32(s, "kimi-k3.attention.head_count", 2);
    if (variant == CFG_HCK_BADVAL) {
        uint32_t bad[3] = {2, 0, 1};
        skv_arr_i32(s, "kimi-k3.attention.head_count_kv", bad, 3);
    } else
        skv_arr_i32(s, "kimi-k3.attention.head_count_kv", hck, 3);
    skv_f32(s, "kimi-k3.rope.freq_base", 10000.0f);
    skv_f32(s, "kimi-k3.attention.layer_norm_rms_epsilon", 1e-5f);
    skv_u32(s, "kimi-k3.expert_count", 2);
    skv_u32(s, "kimi-k3.expert_used_count", 1);
    skv_u32(s, "kimi-k3.expert_group_used_count", 1);
    skv_u32(s, "kimi-k3.expert_gating_func", 2);
    skv_u32(s, "kimi-k3.attention.key_length", 64);
    skv_u32(s, "kimi-k3.attention.value_length", 32);
    /* 2^20: big enough that token_embd/output (68 B/row) cross the 64 MiB
     * dequant chunk boundary, so the chunked path is exercised by the
     * model bind below. */
    skv_u32(s, "kimi-k3.vocab_size", FIX_VOCAB);
    skv_u32(s, "kimi-k3.ssm.conv_kernel", 2);
    skv_u32(s, "kimi-k3.kda.head_dim", 32);
    skv_f32(s, "kimi-k3.kda.gate_lower_bound", -5.0f);
    skv_u32(s, "kimi-k3.attention.q_lora_rank", 32);
    skv_u32(s, "kimi-k3.attention.kv_lora_rank", 32);
    skv_u32(s, "kimi-k3.rope.dimension_count", 32);
    skv_u32(s, "kimi-k3.attention.key_length_mla", 64);
    skv_u32(s, "kimi-k3.attention.value_length_mla", 32);
    skv_u32(s, "kimi-k3.expert_feed_forward_length", 64);
    skv_u32(s, "kimi-k3.expert_shared_count", 1);
    skv_u32(s, "kimi-k3.leading_dense_block_count", 1);
    skv_f32(s, "kimi-k3.expert_weights_scale", 1.0f);
    skv_bool(s, "kimi-k3.expert_weights_norm", 1);
    skv_u32(s, "kimi-k3.expert_latent_length", 64);
    skv_f32(s, "kimi-k3.activation.situ_beta", 4.0f);
    skv_f32(s, "kimi-k3.activation.situ_linear_beta", 25.0f);
    skv_u32(s, "kimi-k3.attn_res.block_size", 2);
}

static char g_dir[256];

static void write_fixture(const Shard *s1, const Shard *s2)
{
    snprintf(g_dir, sizeof g_dir, "/tmp/k3ggufbindXXXXXX");
    if (!mkdtemp(g_dir)) {
        printf("  FAIL  cannot create fixture dir\n");
        fails++;
        return;
    }
    char p[512];
    snprintf(p, sizeof p, "%s/s1.gguf", g_dir);
    FILE *f = fopen(p, "wb");
    if (f) {
        fwrite(s1->b.b, 1, s1->b.n, f);
        fclose(f);
    }
    snprintf(p, sizeof p, "%s/s2.gguf", g_dir);
    f = fopen(p, "wb");
    if (f) {
        fwrite(s2->b.b, 1, s2->b.n, f);
        fclose(f);
    }
}

static void cleanup_fixture(void)
{
    char p[512];
    snprintf(p, sizeof p, "%s/s1.gguf", g_dir);
    unlink(p);
    snprintf(p, sizeof p, "%s/s2.gguf", g_dir);
    unlink(p);
    rmdir(g_dir);
}

/* The synthetic model: 3 layers (dense KDA, KDA MoE, MLA MoE) + model level.
 * dims: H=64 P=64 D=32 CK=2 QL=32 KVL=32 QN=32 QR=32 VH=32 NH=2 E=2 L=64 I=64
 * SI=64 DI=64 VOC=64. Returns the number of tensors registered. */
static void build_model(Shard *s1, Shard *s2, int variant)
{
    const uint64_t H[] = {64}, HN[] = {64, 64}, P[] = {64, 64}, D32[] = {32};
    const uint64_t HH2[] = {2}, HD[] = {64, 32}, DH[] = {32, 64}, HHH[] = {64, 2};
    const uint64_t CK1P[] = {2, 1, 64}, QL[] = {32}, QLQH[] = {32, 128};
    const uint64_t HKVW[] = {64, 64}, QNKLNH[] = {32, 32, 2};
    const uint64_t KLVHNH[] = {32, 32, 2}, P_H[] = {64, 64};
    const uint64_t HE[] = {64, 2}, E1[] = {2}, HL[] = {64, 64};
    const uint64_t LH[] = {64, 64}, L1[] = {64}, HSI[] = {64, 64};
    const uint64_t SIH[] = {64, 64}, LIE[] = {64, 64, 2}, ILE[] = {64, 64, 2};
    const uint64_t HDI[] = {64, 64}, DIH[] = {64, 64}, HV[] = {64, FIX_VOCAB};

    Buf infos;
    memset(&infos, 0, sizeof infos);
    Reg regs[128];
    int n = 0;

    /* model level */
    reg_tensor(&infos, &regs[n++], "token_embd.weight", 2, HV, 8);
    reg_tensor(&infos, &regs[n++], "output.weight", 2, HV, 8);
    reg_tensor(&infos, &regs[n++], "output_norm.weight", 1, H, 0);
    reg_tensor(&infos, &regs[n++], "output_res_score.weight", 1, H, 0);

    for (int L = 0; L < 3; L++) {
        char nm[96];
        const int mla = (L == 2), dense = (L == 0), moe = !dense;
        snprintf(nm, sizeof nm, "blk.%d.attn_norm.weight", L);
        reg_tensor(&infos, &regs[n++], nm, 1, H, 0);
        snprintf(nm, sizeof nm, "blk.%d.attn_res_score.weight", L);
        reg_tensor(&infos, &regs[n++], nm, 1, H, 0);
        snprintf(nm, sizeof nm, "blk.%d.ffn_norm.weight", L);
        reg_tensor(&infos, &regs[n++], nm, 1, H, 0);
        snprintf(nm, sizeof nm, "blk.%d.ffn_res_score.weight", L);
        reg_tensor(&infos, &regs[n++], nm, 1, H, 0);
        snprintf(nm, sizeof nm, "blk.%d.attn_output.weight", L);
        reg_tensor(&infos, &regs[n++], nm, 2, P_H, 8);
        if (mla) {
            snprintf(nm, sizeof nm, "blk.%d.attn_gate.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HN, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_k_b.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, QNKLNH, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_kv_a_mqa.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HKVW, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_kv_a_norm.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 1, D32, 0);
            snprintf(nm, sizeof nm, "blk.%d.attn_q_a.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HD, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_q_a_norm.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 1, QL, 0);
            snprintf(nm, sizeof nm, "blk.%d.attn_q_b.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, QLQH, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_v_b.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, KLVHNH, 8);
        } else {
            snprintf(nm, sizeof nm, "blk.%d.attn_q.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HN, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_k.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HN, 8);
            snprintf(nm, sizeof nm, "blk.%d.attn_v.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HN, 8);
            snprintf(nm, sizeof nm, "blk.%d.ssm_a", L);
            reg_tensor(&infos, &regs[n++], nm, 1, HH2, 0);
            /* The real checkpoint ships ssm_a FOLDED as -exp(A_log); write the
             * fold of the known ALOG_TRUE values so the bind's unfold can be
             * asserted against real numbers. */
            {
                float ssm[2];
                for (int i = 0; i < 2; i++) ssm[i] = -expf(ALOG_TRUE[i]);
                memcpy(regs[n - 1].data, ssm, sizeof ssm);
            }
            snprintf(nm, sizeof nm, "blk.%d.ssm_beta.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HHH, 0);
            snprintf(nm, sizeof nm, "blk.%d.ssm_conv1d_q.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, CK1P, 0);
            snprintf(nm, sizeof nm, "blk.%d.ssm_conv1d_k.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, CK1P, 0);
            snprintf(nm, sizeof nm, "blk.%d.ssm_conv1d_v.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, CK1P, 0);
            snprintf(nm, sizeof nm, "blk.%d.ssm_dt.bias", L);
            reg_tensor(&infos, &regs[n++], nm, 1, P, 0);
            snprintf(nm, sizeof nm, "blk.%d.ssm_f_a.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HD, 8);
            snprintf(nm, sizeof nm, "blk.%d.ssm_f_b.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, DH, 8);
            snprintf(nm, sizeof nm, "blk.%d.ssm_g.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HN, 8);
            snprintf(nm, sizeof nm, "blk.%d.ssm_norm.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 1, D32, 0);
        }
        if (moe) {
            snprintf(nm, sizeof nm, "blk.%d.exp_probs_b.bias", L);
            reg_tensor(&infos, &regs[n++], nm, 1, E1, 0);
            snprintf(nm, sizeof nm, "blk.%d.ffn_gate_inp.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HE, 0);
            snprintf(nm, sizeof nm, "blk.%d.ffn_gate_exps.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, LIE, 19);
            snprintf(nm, sizeof nm, "blk.%d.ffn_up_exps.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, LIE, 19);
            snprintf(nm, sizeof nm, "blk.%d.ffn_down_exps.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 3, ILE, 19);
            snprintf(nm, sizeof nm, "blk.%d.ffn_routed_down.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HL, 8);
            snprintf(nm, sizeof nm, "blk.%d.ffn_routed_norm.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 1, L1, 0);
            snprintf(nm, sizeof nm, "blk.%d.ffn_routed_up.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, LH, 8);
            snprintf(nm, sizeof nm, "blk.%d.ffn_gate_shexp.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HSI, 8);
            snprintf(nm, sizeof nm, "blk.%d.ffn_up_shexp.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HSI, 8);
            snprintf(nm, sizeof nm, "blk.%d.ffn_down_shexp.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, SIH, 8);
        } else {
            snprintf(nm, sizeof nm, "blk.%d.ffn_gate.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HDI, 8);
            snprintf(nm, sizeof nm, "blk.%d.ffn_up.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, HDI, 8);
            snprintf(nm, sizeof nm, "blk.%d.ffn_down.weight", L);
            reg_tensor(&infos, &regs[n++], nm, 2, DIH, 8);
        }
    }

    /* shard 1: metadata only */
    shard_init(s1, 0);
    cfg_kv(s1, variant);
    skv_u16(s1, "split.no", 0);
    skv_i32(s1, "split.tensors.count", n);
    skv_u16(s1, "split.count", 2);
    shard_finish(s1);

    /* shard 2: all tensors */
    shard_init(s2, (uint64_t)n);
    skv_u16(s2, "split.no", 1);
    skv_i32(s2, "split.tensors.count", n);
    skv_u16(s2, "split.count", 2);
    emit_tensors(s2, regs, n);

    for (int i = 0; i < n; i++) {
        free(regs[i].data);
        free((char *)regs[i].name);
    }
    free(infos.b);
}

/* ------------------------------------------------- requant golden fixture --- */
/* Format: "K3MX" u32 version u32 ncases; per case u32 rows u32 cols,
 * f32 w[], u8 packed[rows*cols/2], u8 scales[rows*cols/32]. */
static int run_requant_goldens(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        printf("  FAIL  cannot open %s\n", path);
        return 1;
    }
    unsigned char hdr[12];
    if (fread(hdr, 1, 12, f) != 12 || memcmp(hdr, "K3MX", 4) != 0) {
        printf("  FAIL  requant golden header\n");
        fclose(f);
        return 1;
    }
    uint32_t version, ncases;
    memcpy(&version, hdr + 4, 4);
    memcpy(&ncases, hdr + 8, 4);
    if (version != 1) {
        printf("  FAIL  requant golden version %u, expected 1\n", version);
        fclose(f);
        return 1;
    }
    for (uint32_t c = 0; c < ncases; c++) {
        uint32_t rows, cols;
        if (fread(&rows, 4, 1, f) != 1 || fread(&cols, 4, 1, f) != 1) {
            printf("  FAIL  requant case %u header\n", c);
            fclose(f);
            return 1;
        }
        const size_t nw     = (size_t)rows * cols;
        float *w            = (float *)malloc(nw * 4);
        unsigned char *pk   = (unsigned char *)malloc(nw / 2);
        unsigned char *sc   = (unsigned char *)malloc(nw / 32);
        unsigned char *expk = (unsigned char *)malloc(nw / 2);
        unsigned char *exps = (unsigned char *)malloc(nw / 32);
        if (!w || !pk || !sc || !expk || !exps) {
            printf("  FAIL  requant case %u oom\n", c);
            return 1;
        }
        if (fread(w, 4, nw, f) != nw || fread(expk, 1, nw / 2, f) != nw / 2 ||
            fread(exps, 1, nw / 32, f) != nw / 32) {
            printf("  FAIL  requant case %u payload\n", c);
            return 1;
        }
        const int rc = k3_mxfp4_quant(pk, sc, w, (int)rows, (int)cols);
        if (rc != 0) {
            printf("  FAIL  requant case %u rejected\n", c);
            fails++;
        } else if (memcmp(pk, expk, nw / 2) || memcmp(sc, exps, nw / 32)) {
            printf("  FAIL  requant case %u (%ux%u) bits differ from the numpy "
                   "reference\n",
                   c, rows, cols);
            fails++;
        }
        free(w);
        free(pk);
        free(sc);
        free(expk);
        free(exps);
    }
    fclose(f);
    if (!fails) printf("  ok    requant goldens: %u cases bit-identical\n", ncases);
    return 0;
}

/* ---------------------------------------------------------- part (a): map -- */

static void run_name_map_tests(void)
{
    printf("== gguf map: name translation + shape contracts ==\n");

    /* The synthetic dims' config, for the pure table mechanics. */
    K3Cfg c;
    memset(&c, 0, sizeof c);
    c.hidden         = 64;
    c.n_layers       = 3;
    c.vocab          = 64;
    c.rms_eps        = 1e-5f;
    c.kda_heads      = 2;
    c.kda_head_dim   = 32;
    c.conv_k         = 2;
    c.gate_lb        = -5.0f;
    c.n_heads        = 2;
    c.q_lora         = 32;
    c.kv_lora        = 32;
    c.qk_nope        = 32;
    c.qk_rope        = 32;
    c.v_head         = 32;
    c.mla_out_gate   = 1;
    c.n_experts      = 2;
    c.topk           = 1;
    c.n_shared       = 1;
    c.latent         = 64;
    c.moe_inter      = 64;
    c.routed_scale   = 1.0f;
    c.moe_renorm     = 1;
    c.latent_norm    = 1;
    c.first_dense    = 1;
    c.dense_inter    = 64;
    c.attn_res_block = 2;
    c.situ_b1        = 4.0f;
    c.situ_b2        = 25.0f;
    static int fa[8] = {3};
    c.n_full_attn    = 1;
    c.full_attn      = fa;

    char out[160];
    /* model level */
    ck(k3_gguf_map_translate(&c, -1, "language_model.model.embed_tokens.weight", out,
                             sizeof out) == 0 &&
           !strcmp(out, "token_embd.weight"),
       "model: embed_tokens -> token_embd.weight");
    ck(k3_gguf_map_translate(&c, -1, "language_model.lm_head.weight", out, sizeof out) ==
               0 &&
           !strcmp(out, "output.weight"),
       "model: lm_head -> output.weight");
    ck(k3_gguf_map_translate(&c, -1, "language_model.model.norm.weight", out,
                             sizeof out) == 0 &&
           !strcmp(out, "output_norm.weight"),
       "model: norm -> output_norm.weight");
    ck(k3_gguf_map_translate(&c, -1, "language_model.model.output_attn_res_norm.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "output_res_score.weight"),
       "model: out_res_norm -> output_res_score.weight (folded)");
    ck(k3_gguf_map_translate(&c, -1, "language_model.model.output_attn_res_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "(const ones)"),
       "model: out_res_proj -> const ones");

    /* common per-layer families, on a KDA layer */
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.input_"
                             "layernorm.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.0.attn_norm.weight"),
       "layer: input_layernorm -> blk.N.attn_norm.weight");
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.mlp_res_"
                             "norm.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.0.ffn_res_score.weight"),
       "layer: mlp_res_norm -> blk.N.ffn_res_score.weight (folded; the file has "
       "no mlp_res_norm)");
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.mlp_res_"
                             "proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "(const ones)"),
       "layer: mlp_res_proj -> const ones");

    /* KDA family */
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "q_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.attn_q.weight"),
       "KDA: q_proj -> blk.N.attn_q.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "o_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.attn_output.weight"),
       "KDA: o_proj -> blk.N.attn_output.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "g_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_g.weight"),
       "KDA: g_proj -> blk.N.ssm_g.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "A_log",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_a"),
       "KDA: A_log -> blk.N.ssm_a (no .weight)");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "dt_bias",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_dt.bias"),
       "KDA: dt_bias -> blk.N.ssm_dt.bias");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "q_conv1d.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_conv1d_q.weight"),
       "KDA: q_conv1d -> blk.N.ssm_conv1d_q.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "f_a_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_f_a.weight"),
       "KDA: f_a_proj -> blk.N.ssm_f_a.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "b_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_beta.weight"),
       "KDA: b_proj -> blk.N.ssm_beta.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "o_norm.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ssm_norm.weight"),
       "KDA: o_norm -> blk.N.ssm_norm.weight");

    /* MLA family */
    ck(k3_gguf_map_translate(&c, 2,
                             "language_model.model.layers.2.self_attn."
                             "q_a_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.2.attn_q_a.weight"),
       "MLA: q_a_proj -> blk.N.attn_q_a.weight");
    ck(k3_gguf_map_translate(&c, 2,
                             "language_model.model.layers.2.self_attn."
                             "kv_a_proj_with_mqa.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.2.attn_kv_a_mqa.weight"),
       "MLA: kv_a_proj_with_mqa -> blk.N.attn_kv_a_mqa.weight");
    ck(k3_gguf_map_translate(&c, 2,
                             "language_model.model.layers.2.self_attn."
                             "kv_b_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "(composite kv_b)"),
       "MLA: kv_b_proj -> composite (attn_k_b transposed + attn_v_b)");
    ck(k3_gguf_map_translate(&c, 2,
                             "language_model.model.layers.2.self_attn."
                             "g_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.2.attn_gate.weight"),
       "MLA: g_proj -> blk.N.attn_gate.weight");

    /* MoE family */
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.block_sparse_"
                             "moe.gate.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ffn_gate_inp.weight"),
       "MoE: gate -> blk.N.ffn_gate_inp.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.block_sparse_"
                             "moe.gate.e_score_correction_bias",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.exp_probs_b.bias"),
       "MoE: e_score_correction_bias -> blk.N.exp_probs_b.bias");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.block_sparse_"
                             "moe.routed_expert_up_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ffn_routed_up.weight"),
       "MoE: routed_expert_up_proj -> blk.N.ffn_routed_up.weight");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.block_sparse_"
                             "moe.shared_experts.down_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.1.ffn_down_shexp.weight"),
       "MoE: shared_experts.down_proj -> blk.N.ffn_down_shexp.weight");

    /* dense family */
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.mlp.gate_"
                             "proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.0.ffn_gate.weight"),
       "dense: mlp.gate_proj -> blk.N.ffn_gate.weight");
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.mlp.down_"
                             "proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.0.ffn_down.weight"),
       "dense: mlp.down_proj -> blk.N.ffn_down.weight");

    /* family disambiguation: g_proj is ssm_g on KDA, attn_gate on MLA */
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.self_attn."
                             "g_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.0.ssm_g.weight"),
       "KDA g_proj resolves to ssm_g, not attn_gate");
    ck(k3_gguf_map_translate(&c, 2,
                             "language_model.model.layers.2.self_attn."
                             "g_proj.weight",
                             out, sizeof out) == 0 &&
           !strcmp(out, "blk.2.attn_gate.weight"),
       "MLA g_proj resolves to attn_gate, not ssm_g");
    /* the MoE g_proj spelling does not exist on a dense layer */
    ck(k3_gguf_map_translate(&c, 0,
                             "language_model.model.layers.0.block_sparse_"
                             "moe.gate.weight",
                             out, sizeof out) != 0,
       "MoE gate has no contract entry on the dense layer");

    /* unknown names fail loud */
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.self_attn."
                             "z_proj.weight",
                             out, sizeof out) != 0,
       "unknown engine family rejected");
    ck(k3_gguf_map_translate(&c, -1, "language_model.model.bogus.weight", out,
                             sizeof out) != 0,
       "unknown model-level name rejected");
    ck(k3_gguf_map_translate(&c, 1,
                             "language_model.model.layers.1.block_sparse_"
                             "moe.experts.3.w1.weight_packed",
                             out, sizeof out) != 0,
       "expert names are NOT name-mapped (they feed the expert source)");

    /* ---- shape contracts: positives + adversarial (pure, no file) ---- */
    K3Gguf fake;
    memset(&fake, 0, sizeof fake);
    K3Tensor t;
    uint16_t gtype;
    fake.t     = &t;
    fake.gtype = &gtype;

    memset(&t, 0, sizeof t);
    t.name     = (char *)"blk.1.attn_q.weight";
    t.ndim     = 2;
    t.shape[0] = 64;
    t.shape[1] = 64;
    t.nbytes   = 4352; /* ceil(64/32)*34 * 64 */
    gtype      = K3_GGUF_TYPE_Q8_0;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_proj.weight",
                         &t) == 0,
       "shape contract: correct Q8_0 tensor passes");
    gtype = K3_GGUF_TYPE_F32;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_proj.weight",
                         &t) != 0,
       "shape contract: wrong ggml type fails");
    gtype      = K3_GGUF_TYPE_Q8_0;
    t.shape[1] = 32;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_proj.weight",
                         &t) != 0,
       "shape contract: transposed dims fail (numel-only would pass)");
    t.shape[1] = 64;
    t.nbytes   = 4353;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_proj.weight",
                         &t) != 0,
       "shape contract: nbytes off by one fails");
    t.nbytes   = 4352;
    t.ndim     = 3;
    t.shape[2] = 1;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_proj.weight",
                         &t) != 0,
       "shape contract: extra dim fails");
    t.ndim     = 2;
    t.shape[2] = 0;
    /* the conv contract is 3-D [conv_k, 1, P] */
    memset(&t, 0, sizeof t);
    t.name     = (char *)"blk.1.ssm_conv1d_q.weight";
    t.ndim     = 3;
    t.shape[0] = 2;
    t.shape[1] = 1;
    t.shape[2] = 64;
    t.nbytes   = 2 * 1 * 64 * 4;
    gtype      = K3_GGUF_TYPE_F32;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_conv1d.weight",
                         &t) == 0,
       "shape contract: conv 3-D [conv_k,1,P] passes");
    t.shape[1] = 2;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "q_conv1d.weight",
                         &t) != 0,
       "shape contract: conv middle dim != 1 fails");
    /* ssm_a: the file ships kda_heads values (2), engine pads to kda_head_dim */
    memset(&t, 0, sizeof t);
    t.name     = (char *)"blk.1.ssm_a";
    t.ndim     = 1;
    t.shape[0] = 2;
    t.nbytes   = 8;
    gtype      = K3_GGUF_TYPE_F32;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "A_log",
                         &t) == 0,
       "shape contract: ssm_a [kda_heads] passes");
    t.shape[0] = 3;
    ck(k3_gguf_map_check(&c, &fake, 1,
                         "language_model.model.layers.1.self_attn."
                         "A_log",
                         &t) != 0,
       "shape contract: ssm_a with the wrong head count fails");

    /* expert-slice window arithmetic (pure) */
    {
        const int64_t le[4] = {3584, 3072, 896, 1};
        const int64_t de[4] = {3072, 3584, 896, 1};
        const int64_t gb    = k3_gguf_dequant_nbytes(K3_GGUF_TYPE_IQ1_S, 3, le);
        const int64_t db    = k3_gguf_dequant_nbytes(K3_GGUF_TYPE_IQ1_S, 3, de);
        ck(gb == 1926758400 && db == 1926758400,
           "expert window: real gate/up and down tensors are both 1,926,758,400 B");
        ck(gb / 896 == 2150400 && db / 896 == 2150400,
           "expert window: per-expert window is 2,150,400 B (contiguous)");
        ck(gb % 896 == 0, "expert window: whole windows only");
        const int64_t per = 2150400;
        ck(7 * per == 15052800 && 8 * per == 17203200,
           "expert window: expert 8 starts exactly where expert 7 ends");
    }
}

/* -------------------------------------------------- part (c): synthetic run */

static void run_synthetic_fixture(void)
{
    printf("== gguf bind: synthetic 3-layer fixture ==\n");

    Shard s1 = {0}, s2 = {0};
    build_model(&s1, &s2, CFG_OK);
    write_fixture(&s1, &s2);

    K3Gguf g;
    K3Cfg c;
    static int fa[8];
    if (k3_gguf_open(&g, g_dir) != 0) {
        printf("  FAIL  synthetic open\n");
        fails++;
        cleanup_fixture();
        free(s1.b.b);
        free(s2.b.b);
        return;
    }
    if (!k3_gguf_cfg(&g, &c, fa, 8)) {
        printf("  FAIL  synthetic cfg\n");
        fails++;
        k3_gguf_close(&g);
        cleanup_fixture();
        free(s1.b.b);
        free(s2.b.b);
        return;
    }
    ck(c.hidden == 64 && c.n_layers == 3 && c.vocab == (int)FIX_VOCAB,
       "synthetic cfg dims");
    ck(c.kda_heads == 2 && c.kda_head_dim == 32 && c.conv_k == 2, "synthetic cfg kda");
    ck(c.q_lora == 32 && c.kv_lora == 32 && c.qk_nope == 32 && c.qk_rope == 32 &&
           c.v_head == 32,
       "synthetic cfg mla");
    ck(c.n_experts == 2 && c.topk == 1 && c.latent == 64 && c.moe_inter == 64,
       "synthetic cfg moe");
    ck(c.first_dense == 1 && c.dense_inter == 64, "synthetic cfg dense");
    ck(c.n_full_attn == 1 && fa[0] == 3, "synthetic cfg layer map (layer 2 MLA)");

    /* full contract coverage: every tensor in the fixture is validated */
    const int checked = k3_gguf_validate_all(&g, &c);
    ck(checked == g.nt, "validate_all covers every tensor in the fixture");
    ck(g.nt == 78, "fixture holds 78 tensors");

    K3GgufBind b;
    ck(k3_gguf_bind_init(&b, &g, &c) == 0, "bind init");

    /* layer bytes: spot-check the dense layer's components */
    const int64_t lb0 = k3_gguf_layer_bytes(&b, 0);
    const int64_t lb1 = k3_gguf_layer_bytes(&b, 1);
    const int64_t lb2 = k3_gguf_layer_bytes(&b, 2);
    ck(lb0 > 0 && lb1 > 0 && lb2 > 0, "layer bytes resolve for all three layers");
    if (lb0 > 0 && lb1 > 0) {
        /* dense swaps the 3 dense mats for the 11 MoE tensors: the difference is
         * 3*[64][64]bf16 - (gate_inp 512 + bias 8 + down/up 2*8192 + norm 256 +
         * 3 shared 3*8192) = -17160. */
        ck(lb0 - lb1 ==
               3 * 64 * 64 * 2 - (512 + 8 + 2 * 64 * 64 * 2 + 256 + 3 * 64 * 64 * 2),
           "dense layer bytes = KDA + 3 dense mats, MoE layer = KDA + MoE tensors");
        /* MLA: q_a/q_b/kv_a/kv_b/gate instead of q/k/v/g + convs + f_a/f_b + b */
        ck(lb2 > 0 && lb2 != lb1, "MLA layer differs from KDA layer");
    }
    /* the ones vector and A_log padding are part of every layer */
    ck(lb1 > 64 * 4 + 32 * 4, "layer bytes include ones vector + padded A_log");

    /* budget gate: the buffer must fit the largest layer, fail loud otherwise */
    const int64_t mx = k3_gguf_layer_bytes_max(&b, 3);
    ck(mx == (lb0 > lb1 ? (lb0 > lb2 ? lb0 : lb2) : (lb1 > lb2 ? lb1 : lb2)),
       "layer bytes max = the largest layer");
    ck(k3_gguf_bind_alloc(&b, 3, mx) == 0, "bind alloc fits the max layer");
    ck(k3_gguf_bind_alloc(&b, 3, mx - 1) != 0, "bind alloc refuses a too-small "
                                               "--trunk-gb budget");

    /* ---- layer binds + data verification ----
     * NOTE: the layer buffer is REUSABLE - L0's pointers are only valid until
     * the next bind - so each layer's data is checked immediately after its
     * own bind. */
    K3LayerBind L0, L1, L2;
    ck(k3_gguf_bind_layer(&b, 0, &L0) == 0, "bind layer 0 (dense KDA)");
    ck(L0.lay.wdt == K3_WBF16 && L0.lay.kda && !L0.lay.mla && !L0.lay.moe,
       "layer 0 tagged WBF16 KDA dense");

    /* Data checks against independently dequantized raw bytes. */
    {
        const K3Tensor *t  = k3_gguf_find(&g, "blk.0.attn_q.weight");
        uint16_t *expect   = (uint16_t *)malloc((size_t)t->nbytes / 34 * 64 * 2);
        unsigned char *raw = (unsigned char *)malloc((size_t)t->nbytes);
        K3GgufTensor gt;
        memset(&gt, 0, sizeof gt);
        gt.ggml_type = K3_GGUF_TYPE_Q8_0;
        gt.ndim      = 2;
        gt.ne[0]     = 64;
        gt.ne[1]     = 64;
        gt.nbytes    = t->nbytes;
        gt.data      = raw;
        K3GgufExpect ex;
        memset(&ex, 0, sizeof ex);
        ex.ndim  = 2;
        ex.ne[0] = 64;
        ex.ne[1] = 64;
        if (k3_gguf_read(&g, t, raw) == t->nbytes &&
            k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, expect, &ex) == 0) {
            ck(L0.kda.q && memcmp(L0.kda.q, expect, 64 * 64 * 2) == 0,
               "layer 0 q_proj equals the independent dequant");
        } else {
            printf("  FAIL  cannot recompute layer 0 q_proj\n");
            fails++;
        }
        free(raw);
        free(expect);
    }

    /* F32 vector: in_norm is the fixture's raw floats, bit-exact */
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.0.attn_norm.weight");
        float *expect     = (float *)malloc((size_t)t->nbytes);
        if (k3_gguf_read(&g, t, expect) == t->nbytes) {
            int same =
                L0.lay.in_norm && !memcmp(L0.lay.in_norm, expect, (size_t)t->nbytes);
            ck(same, "layer 0 in_norm equals the fixture's fp32 bytes");
        } else {
            printf("  FAIL  cannot read blk.0.attn_norm.weight\n");
            fails++;
        }
        free(expect);
    }

    /* A_log: the file stores the FOLDED ssm_a = -exp(A_log); the bind must
     * recover the KNOWN A_log values (ln(-ssm_a)), with the tail padded to
     * kda_head_dim(32) with zeros. This is the A_log unfold correctness
     * check of the fix wave (architect (c)); the fold itself is also asserted
     * to be negative, as the real file's 96 values are. */
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.0.ssm_a");
        float *expect     = (float *)malloc((size_t)t->nbytes);
        if (k3_gguf_read(&g, t, expect) == t->nbytes) {
            int head_ok = L0.kda.A_log != NULL;
            for (int i = 0; head_ok && i < 2; i++) {
                const float got  = L0.kda.A_log[i];
                const float want = ALOG_TRUE[i];
                /* logf/expf round-trip is not guaranteed bit-exact; 1e-6
                 * relative is 10+ ulps of headroom on the fp32 unfold. */
                if (fabsf(got - want) > 1e-6f * fmaxf(fabsf(want), 1e-6f))
                    head_ok = 0;
            }
            int tail_ok = L0.kda.A_log != NULL;
            for (int i = 2; tail_ok && i < 32; i++)
                if (L0.kda.A_log[i] != 0.0f) tail_ok = 0;
            int fold_ok = 1;
            for (int i = 0; i < 2; i++)
                if (!(expect[i] < 0.0f)) fold_ok = 0;
            ck(head_ok && tail_ok && fold_ok,
               "A_log: bind recovers ln(-ssm_a) of the known values + zero "
               "tail");
        } else {
            printf("  FAIL  cannot read blk.0.ssm_a\n");
            fails++;
        }
        free(expect);
    }

    /* A_log unfold unit: boundary and fail-loud, against the REAL file read
     * path. Patch the fixture's blk.0.ssm_a bytes on disk and re-bind: the
     * boundary ssm_a = -1.0 must unfold to exactly 0.0 (ln(1)), and a
     * non-negative ssm_a must fail the bind loud. The original bytes are
     * restored afterwards so the later reuse checks see a pristine fixture.
     * Every patch is fflush()ed before the bind: the re-bind reads through
     * the engine's own pread path, which must see the new bytes. */
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.0.ssm_a");
        float orig[2];
        if (!t || k3_gguf_read(&g, t, orig) != t->nbytes) {
            ck(0, "A_log unfold unit: read the original ssm_a");
        } else {
            char p[512];
            snprintf(p, sizeof p, "%s/s2.gguf", g_dir);
            FILE *f = fopen(p, "r+b");
            if (!f) {
                ck(0, "A_log unfold unit: open the fixture for patching");
            } else {
                /* boundary: -1.0 -> A_log = 0.0 exactly */
                const float minus_one = -1.0f;
                fseek(f, (long)t->off, SEEK_SET);
                int wrote = fwrite(&minus_one, 4, 1, f) == 1;
                if (wrote) wrote = fflush(f) == 0;
                if (!wrote) {
                    ck(0, "A_log boundary: patch ssm_a[0] = -1.0");
                } else {
                    K3LayerBind Lb;
                    if (k3_gguf_bind_layer(&b, 0, &Lb) != 0 || !Lb.lay.kda ||
                        !Lb.kda.A_log) {
                        ck(0, "A_log boundary: re-bind layer 0");
                    } else {
                        ck(Lb.kda.A_log[0] == 0.0f &&
                               fabsf(Lb.kda.A_log[1] - ALOG_TRUE[1]) <
                                   1e-6f * fmaxf(fabsf(ALOG_TRUE[1]), 1e-6f),
                           "A_log boundary: ssm_a = -1.0 unfolds to exactly "
                           "0.0");
                    }
                    k3_bind_free(&Lb);
                }
                /* fail-loud: a NON-NEGATIVE ssm_a (corrupt/retrained file)
                 * must be rejected, not silently passed or NaN'd */
                const float plus_one = 1.0f;
                fseek(f, (long)t->off, SEEK_SET);
                wrote = fwrite(&plus_one, 4, 1, f) == 1;
                if (wrote) wrote = fflush(f) == 0;
                if (!wrote) {
                    ck(0, "A_log fail-loud: patch ssm_a[0] = +1.0");
                } else {
                    K3LayerBind Lb;
                    const int rc = k3_gguf_bind_layer(&b, 0, &Lb);
                    ck(rc != 0, "A_log fail-loud: non-negative ssm_a fails "
                                "the bind");
                    k3_bind_free(&Lb);
                }
                /* zero is equally corrupt: A_log would be ln(0) = -inf */
                const float zero = 0.0f;
                fseek(f, (long)t->off, SEEK_SET);
                wrote = fwrite(&zero, 4, 1, f) == 1;
                if (wrote) wrote = fflush(f) == 0;
                if (!wrote) {
                    ck(0, "A_log fail-loud: patch ssm_a[0] = 0.0");
                } else {
                    K3LayerBind Lb;
                    const int rc = k3_gguf_bind_layer(&b, 0, &Lb);
                    ck(rc != 0, "A_log fail-loud: zero ssm_a fails the bind");
                    k3_bind_free(&Lb);
                }
                /* restore: the reuse checks later re-bind layer 0 and must
                 * see the pristine fixture */
                fseek(f, (long)t->off, SEEK_SET);
                fwrite(orig, 4, 2, f);
                fflush(f);
                fclose(f);
            }
        }
    }

    /* b_proj: F32 on disk, bf16 in the engine */
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.0.ssm_beta.weight");
        float *raw        = (float *)malloc((size_t)t->nbytes);
        uint16_t *expect  = (uint16_t *)malloc((size_t)t->nbytes / 2);
        if (k3_gguf_read(&g, t, raw) == t->nbytes) {
            for (int64_t i = 0; i < t->nbytes / 4; i++)
                expect[i] = k3_gguf_f32_to_bf16(raw[i]);
            ck(L0.kda.b && memcmp(L0.kda.b, expect, (size_t)t->nbytes / 2) == 0,
               "b_proj F32 -> bf16 conversion matches the reference");
        } else {
            printf("  FAIL  cannot read blk.0.ssm_beta.weight\n");
            fails++;
        }
        free(raw);
        free(expect);
    }

    /* res folds: norm side = the folded vector, proj side = constant 1.0 */
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.0.attn_res_score.weight");
        float *fold       = (float *)malloc((size_t)t->nbytes);
        if (k3_gguf_read(&g, t, fold) == t->nbytes) {
            int n_ok = L0.lay.attn_res_norm &&
                       !memcmp(L0.lay.attn_res_norm, fold, (size_t)t->nbytes);
            int p_ok = L0.lay.attn_res_proj != NULL;
            for (int i = 0; p_ok && i < 64; i++)
                if (L0.lay.attn_res_proj[i] != 1.0f) p_ok = 0;
            ck(n_ok && p_ok, "attn_res: norm = folded score, proj = ones");
        } else {
            printf("  FAIL  cannot read blk.0.attn_res_score.weight\n");
            fails++;
        }
        free(fold);
    }
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.0.ffn_res_score.weight");
        float *fold       = (float *)malloc((size_t)t->nbytes);
        if (k3_gguf_read(&g, t, fold) == t->nbytes) {
            int n_ok = L0.lay.mlp_res_norm &&
                       !memcmp(L0.lay.mlp_res_norm, fold, (size_t)t->nbytes);
            int p_ok = L0.lay.mlp_res_proj != NULL;
            for (int i = 0; p_ok && i < 64; i++)
                if (L0.lay.mlp_res_proj[i] != 1.0f) p_ok = 0;
            ck(n_ok && p_ok, "mlp_res: norm = folded ffn_res_score, proj = ones");
        } else {
            printf("  FAIL  cannot read blk.0.ffn_res_score.weight\n");
            fails++;
        }
        free(fold);
    }
    ck(L0.lay.dense_gate && L0.lay.dense_up && L0.lay.dense_down,
       "layer 0 dense gate/up/down bound");

    /* ---- layer 1: KDA MoE ---- */
    ck(k3_gguf_bind_layer(&b, 1, &L1) == 0, "bind layer 1 (KDA MoE)");
    ck(L1.lay.wdt == K3_WBF16 && L1.lay.kda && L1.lay.moe, "layer 1 KDA MoE");
    {
        const K3Tensor *t = k3_gguf_find(&g, "blk.1.ffn_gate_inp.weight");
        float *expect     = (float *)malloc((size_t)t->nbytes);
        if (k3_gguf_read(&g, t, expect) == t->nbytes) {
            ck(L1.moe.gate && !memcmp(L1.moe.gate, expect, (size_t)t->nbytes),
               "layer 1 router gate equals the fixture's fp32 bytes");
        } else {
            printf("  FAIL  cannot read blk.1.ffn_gate_inp.weight\n");
            fails++;
        }
        free(expect);
    }

    /* ---- layer 2: MLA MoE ---- */
    ck(k3_gguf_bind_layer(&b, 2, &L2) == 0, "bind layer 2 (MLA MoE)");
    ck(L2.lay.wdt == K3_WBF16 && L2.lay.mla && L2.lay.moe, "layer 2 MLA MoE");
    /* kv_b: reassembled from attn_k_b (transposed per head) + attn_v_b */
    {
        const int64_t QN = 32, VH = 32, KL = 32, H = 2;
        const K3Tensor *kt = k3_gguf_find(&g, "blk.2.attn_k_b.weight");
        const K3Tensor *vt = k3_gguf_find(&g, "blk.2.attn_v_b.weight");
        uint16_t *expect   = (uint16_t *)malloc((size_t)(H * (QN + VH) * KL) * 2);
        uint16_t *ks       = (uint16_t *)malloc((size_t)(H * KL * QN) * 2);
        uint16_t *vs       = (uint16_t *)malloc((size_t)(H * VH * KL) * 2);
        unsigned char *raw = (unsigned char *)malloc((size_t)kt->nbytes);
        int ok             = 1;
        K3GgufTensor gt;
        K3GgufExpect ex;
        if (k3_gguf_read(&g, kt, raw) != kt->nbytes) ok = 0;
        memset(&gt, 0, sizeof gt);
        gt.ggml_type = K3_GGUF_TYPE_Q8_0;
        gt.ndim      = 3;
        gt.ne[0]     = QN;
        gt.ne[1]     = KL;
        gt.ne[2]     = H;
        gt.nbytes    = kt->nbytes;
        gt.data      = raw;
        memset(&ex, 0, sizeof ex);
        ex.ndim  = 3;
        ex.ne[0] = QN;
        ex.ne[1] = KL;
        ex.ne[2] = H;
        if (k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, ks, &ex) != 0) ok = 0;
        if (k3_gguf_read(&g, vt, raw) != vt->nbytes) ok = 0;
        gt.ne[0]  = KL;
        gt.ne[1]  = VH;
        gt.ne[2]  = H;
        gt.nbytes = vt->nbytes;
        ex.ne[0]  = KL;
        ex.ne[1]  = VH;
        ex.ne[2]  = H;
        if (k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, vs, &ex) != 0) ok = 0;
        if (ok) {
            for (int64_t h = 0; h < H; h++) {
                for (int64_t i = 0; i < QN; i++)
                    for (int64_t j = 0; j < KL; j++)
                        expect[(size_t)(h * (QN + VH) + i) * KL + j] =
                            ks[(size_t)(h * KL + j) * QN + i];
                for (int64_t i = 0; i < VH; i++)
                    memcpy(expect + (size_t)(h * (QN + VH) + QN + i) * KL,
                           vs + (size_t)(h * VH + i) * KL, (size_t)KL * 2);
            }
            ck(L2.mla.kv_b &&
                   memcmp(L2.mla.kv_b, expect, (size_t)(H * (QN + VH) * KL) * 2) == 0,
               "kv_b equals the independently reassembled k_b^T + v_b");
        } else {
            printf("  FAIL  cannot recompute kv_b\n");
            fails++;
        }
        free(raw);
        free(expect);
        free(ks);
        free(vs);
    }

    /* ---- layer-buffer REUSE: no stale data across layer boundaries ----
     * What must hold is that every refill REWRITES every tensor: a tensor the
     * refill skipped would keep the previous layer's bytes. Bind layer 0, save
     * two tensors' bytes, bind layer 1 (the same buffer now holds layer 1's
     * data), then re-bind layer 0 and require the saved bytes back exactly. */
    {
        if (!L0.lay.in_norm || !L0.kda.q) {
            printf("  FAIL  reuse test needs bound tensors\n");
            fails++;
        } else {
            /* Bind layer 0 FRESH: the buffer has been through layers 1 and 2
             * since L0's original bind, so its pointers are stale by design. */
            K3LayerBind L0a;
            ck(k3_gguf_bind_layer(&b, 0, &L0a) == 0, "reuse: fresh bind layer 0");
            float in0[64];
            uint16_t q0[64];
            memcpy(in0, L0a.lay.in_norm, sizeof in0);
            memcpy(q0, L0a.kda.q, sizeof q0);
            /* bind layer 1: the buffer must now hold layer 1's bytes */
            K3LayerBind L1b;
            ck(k3_gguf_bind_layer(&b, 1, &L1b) == 0, "reuse: bind layer 1");
            ck(memcmp(L1b.lay.in_norm, in0, sizeof in0) != 0,
               "reuse: layer 1 refill overwrote layer 0's data");
            /* re-bind layer 0: every tensor comes back from the file */
            K3LayerBind L0b;
            ck(k3_gguf_bind_layer(&b, 0, &L0b) == 0, "reuse: re-bind layer 0");
            ck(L0b.lay.in_norm && L0b.kda.q &&
                   memcmp(L0b.lay.in_norm, in0, sizeof in0) == 0 &&
                   memcmp(L0b.kda.q, q0, sizeof q0) == 0,
               "reuse: re-bound layer 0 matches its original values (no stale "
               "bytes)");
            /* the old L1 bind's pointers follow the refill: they now see layer
             * 0's data (re-pointed, never stale). */
            ck(L1b.lay.in_norm && memcmp(L1b.lay.in_norm, in0, sizeof in0) == 0,
               "reuse: L1's old pointers follow the refill");
            k3_bind_free(&L0a);
            k3_bind_free(&L0b);
            k3_bind_free(&L1b);
        }
    }

    /* ---- model bind ---- */
    K3ModelBind mb;
    ck(k3_gguf_bind_model(&b, 1, &mb) == 0, "model bind with lm_head");
    if (mb.embed) {
        const K3Tensor *t  = k3_gguf_find(&g, "token_embd.weight");
        uint16_t *expect   = (uint16_t *)malloc((size_t)FIX_VOCAB * 64 * 2);
        unsigned char *raw = (unsigned char *)malloc((size_t)t->nbytes);
        K3GgufTensor gt;
        K3GgufExpect ex;
        memset(&gt, 0, sizeof gt);
        gt.ggml_type = K3_GGUF_TYPE_Q8_0;
        gt.ndim      = 2;
        gt.ne[0]     = 64;
        gt.ne[1]     = FIX_VOCAB;
        gt.nbytes    = t->nbytes;
        gt.data      = raw;
        memset(&ex, 0, sizeof ex);
        ex.ndim  = 2;
        ex.ne[0] = 64;
        ex.ne[1] = FIX_VOCAB;
        if (k3_gguf_read(&g, t, raw) == t->nbytes &&
            k3_gguf_dequant(&gt, K3_GGUF_DEQ_BF16, expect, &ex) == 0) {
            ck(mb.wdt == K3_WBF16 &&
                   !memcmp(mb.embed, expect, (size_t)FIX_VOCAB * 64 * 2),
               "model: embed equals the independent dequant (chunked)");
        } else {
            printf("  FAIL  cannot recompute embed\n");
            fails++;
        }
        free(raw);
        free(expect);
    }
    ck(mb.lm_head != NULL, "model: lm_head bound");
    ck(mb.out_res_proj != NULL, "model: out_res_proj bound");
    {
        int ones_ok = 1;
        for (int i = 0; i < 64; i++)
            if (mb.out_res_proj[i] != 1.0f) ones_ok = 0;
        ck(ones_ok, "model: out_res_proj is the constant-1.0 vector");
    }
    K3ModelBind mb2;
    ck(k3_gguf_bind_model(&b, 0, &mb2) == 0, "model bind without lm_head");
    ck(mb2.lm_head == NULL && mb2.embed != NULL, "model: want_lm_head=0 skips it");
    k3_bind_model_free(&mb2);
    k3_bind_model_free(&mb);

    /* ---- expert source ---- */
    /* Native IQ1_S storage (fix wave): the slot holds the RAW block bytes of
     * the three windows, 50 B per 256-value block row-padded (64-wide rows
     * pad to one 256 block each): 3 * 64 * 50 = 9600 B per slot. */
    const int64_t slot_b = 3 * 64 * K3_GGUF_IQ1_S_BSZ;
    K3GgufExpertSrc es;
    ck(k3_gguf_expert_src_init(&es, &g, &c, 2 * slot_b) == 0,
       "expert source init with 2 slots");
    ck(es.nslot == 2 && es.slot_bytes == slot_b,
       "expert source geometry: 2 slots of the canonical IQ1_S run size");
    /* a budget below topk+1 slots must fail loud */
    K3GgufExpertSrc es2;
    ck(k3_gguf_expert_src_init(&es2, &g, &c, 1 * slot_b - 1) != 0,
       "expert source refuses a budget below topk+1 slots");
    k3_gguf_expert_src_free(&es2);

    K3ExpertQ q;
    ck(es.src.get(&es.src, 2, 0, &q) == 0, "expert source get(2,0)");
    ck(q.wfmt == K3_EXPERT_IQ1S && q.p1 && q.p2 && q.p3 && !q.s1 && !q.s2 &&
           !q.s3,
       "expert served as native IQ1_S (wfmt tag, no scale pointers)");
    ck(es.misses == 1 && es.hits == 0, "first get is a miss");

    /* slot content == the raw IQ1_S window bytes read independently (no
     * requant, no transform - the fix wave's storage contract) */
    {
        char gate[64], up[64], down[64];
        k3_gguf_expert_names(2, gate, up, down);
        const char *name[3] = {gate, down, up}; /* w1, w2, w3 */
        int ok              = 1;
        for (int m = 0; m < 3; m++) {
            const K3Tensor *gt = k3_gguf_find(&g, name[m]);
            const int64_t per  = gt->nbytes / 2;
            unsigned char *raw = (unsigned char *)malloc((size_t)per);
            K3Tensor win       = *gt;
            win.name           = (char *)"expert window";
            win.off            = gt->off; /* expert 0: the first window */
            win.nbytes         = per;
            if (k3_gguf_read(&g, &win, raw) != per) ok = 0;
            const unsigned char *p = m == 0 ? q.p1 : (m == 1 ? q.p2 : q.p3);
            if (memcmp(p, raw, (size_t)per) != 0) ok = 0;
            free(raw);
        }
        if (ok)
            ck(1, "slot bytes == the raw IQ1_S windows from disk");
        else {
            printf("  FAIL  slot bytes differ from the raw windows\n");
            fails++;
        }
    }

    ck(es.src.get(&es.src, 2, 0, &q) == 0 && es.hits == 1, "second get is a hit");
    ck(es.src.resident(&es.src, 2, 0, NULL) == 1, "resident(2,0) after the hit");
    /* expert 1 fills the SECOND empty slot: no eviction, both resident */
    ck(es.src.get(&es.src, 2, 1, &q) == 0, "get(2,1)");
    ck(es.evictions == 0 && es.src.resident(&es.src, 2, 0, NULL) == 1 &&
           es.src.resident(&es.src, 2, 1, NULL) == 1,
       "two experts fill two slots without evicting");
    /* a THIRD key (layer 1) must evict the LRU slot: expert (2,0) */
    ck(es.src.get(&es.src, 1, 0, &q) == 0, "get(1,0) forces an eviction");
    ck(es.evictions == 1 && es.src.resident(&es.src, 2, 0, NULL) == 0 &&
           es.src.resident(&es.src, 1, 0, NULL) == 1 &&
           es.src.resident(&es.src, 2, 1, NULL) == 1,
       "LRU evicts expert (2,0), keeping (2,1) and (1,0)");

    /* getmany: bring both layer-2 experts resident in one batch */
    {
        const int ids[2] = {0, 1};
        const int got    = es.src.getmany(&es.src, 2, ids, 2);
        ck(got == 2, "getmany brings both experts (evicting layer 1's)");
        ck(es.src.resident(&es.src, 2, 0, NULL) == 1 &&
               es.src.resident(&es.src, 2, 1, NULL) == 1 &&
               es.src.resident(&es.src, 1, 0, NULL) == 0,
           "layer-2 pair resident, layer-1 expert evicted");
        /* duplicate ids in one batch are handled: everything already resident */
        const int dup[3] = {0, 1, 0};
        ck(es.src.getmany(&es.src, 2, dup, 3) == 0, "getmany with all hits");
        ck(es.prefetch_reads == 2, "getmany counted 2 prefetches (k3_cache "
                                   "semantics: not hits/misses)");
        k3_gguf_expert_src_reset_stats(&es);
        ck(es.prefetch_reads == 0 && es.hits == 0 && es.misses == 0,
           "reset_stats clears prefetch_reads with the hits window");
    }

    /* out-of-range requests fail loud, never wrap */
    ck(es.src.get(&es.src, 5, 0, &q) != 0, "layer out of range fails");
    ck(es.src.get(&es.src, 2, 9, &q) != 0, "expert out of range fails");
    ck(es.src.resident(&es.src, 5, 0, NULL) == 0, "resident out of range is 0");

    /* a dense layer has no expert tensors: the request fails loud, never a
     * wrong-layer admit */
    ck(es.src.get(&es.src, 0, 0, &q) != 0,
       "dense layer expert request fails (blk.0 has no ffn_*_exps)");

    k3_gguf_expert_src_free(&es);
    k3_bind_free(&L0);
    k3_bind_free(&L1);
    k3_bind_free(&L2);
    k3_gguf_bind_free(&b);
    k3_gguf_close(&g);
    cleanup_fixture();
    free(s1.b.b);
    free(s2.b.b);

    /* the cfg reject path on the same fixture shape */
    {
        Shard a = {0}, c2 = {0};
        build_model(&a, &c2, CFG_HCK_BADVAL);
        write_fixture(&a, &c2);
        K3Gguf g2;
        K3Cfg c3;
        static int fa2[8];
        if (k3_gguf_open(&g2, g_dir) != 0) {
            printf("  FAIL  bad-cfg fixture open\n");
            fails++;
        } else {
            ck(k3_gguf_cfg(&g2, &c3, fa2, 8) == 0, "cfg rejects a bad head_count_kv");
            k3_gguf_close(&g2);
        }
        cleanup_fixture();
        free(a.b.b);
        free(c2.b.b);
    }
}

/* ---------------------------------------------------------- part (d): gate */

static void run_real_file_gate(void)
{
    printf("== gguf bind (real-file gate, headers only) ==\n");

    const char *dir = getenv("K3_GGUF_REAL");
    if (!dir || !dir[0]) dir = "/workspace/unsloth/Kimi-K3-GGUF/UD-IQ1_S";
    if (access(dir, R_OK) != 0) {
        printf("SKIPPED: no real GGUF at %s (set K3_GGUF_REAL to enable)\n", dir);
        return;
    }

    K3Gguf g;
    K3Cfg c;
    static int fa[128];
    if (k3_gguf_open(&g, dir) != 0) {
        printf("  FAIL  real open\n");
        fails++;
        return;
    }
    if (!k3_gguf_cfg(&g, &c, fa, 128)) {
        printf("  FAIL  real cfg\n");
        fails++;
        k3_gguf_close(&g);
        return;
    }

    /* The contract table must cover EVERY tensor of the file: validate_all
     * resolves each entry per layer and returns the total. */
    const int checked = k3_gguf_validate_all(&g, &c);
    ck(checked == g.nt && g.nt == 2573,
       "validate_all covers all 2573 real tensors (per-dim shapes + types)");

    /* name-map round trips against the REAL index: every family of a KDA MoE
     * layer (1), an MLA MoE layer (4) and the dense layer (0) must resolve to a
     * tensor that actually exists. */
    {
        K3GgufBind b;
        k3_gguf_bind_init(&b, &g, &c);
        int bad = 0;
        for (int L = 0; L < c.n_layers && !bad; L++) {
            const int64_t n = k3_gguf_layer_bytes(&b, L);
            if (n < 0) {
                printf("  FAIL  layer %d fails to resolve\n", L);
                fails++;
                bad = 1;
            }
        }
        ck(!bad, "every real layer resolves against the contract table");
    }

    /* expert geometry on real dims */
    {
        char gate[64], up[64], down[64];
        k3_gguf_expert_names(1, gate, up, down);
        const K3Tensor *t = k3_gguf_find(&g, gate);
        ck(t && t->shape[0] == 3584 && t->shape[1] == 3072 && t->shape[2] == 896,
           "real gate_exps dims (3584, 3072, 896)");
        ck(t && t->nbytes == 1926758400 && t->nbytes % 896 == 0 &&
               t->nbytes / 896 == 2150400,
           "real per-expert window 2,150,400 B, whole windows");
        /* blk.92's experts live in shards 13/14 - the window arithmetic holds
         * there too (cross-shard expert tensors are fine: each tensor is whole
         * in one shard). */
        k3_gguf_expert_names(92, gate, up, down);
        const K3Tensor *d92 = k3_gguf_find(&g, down);
        ck(d92 && d92->nbytes / d92->shape[2] == 2150400,
           "real blk.92 down_exps window arithmetic (shards 13/14)");
    }

    /* adversarial shape on a real tensor: transposed dims must fail */
    {
        const K3Tensor *t = k3_gguf_find(&g, "output.weight");
        if (t) {
            K3Tensor bad = *t;
            int64_t tmp  = bad.shape[0];
            bad.shape[0] = bad.shape[1];
            bad.shape[1] = tmp;
            ck(k3_gguf_map_check(&c, &g, -1, "language_model.lm_head.weight", &bad) != 0,
               "real: transposed lm_head fails the per-dim contract");
        }
    }

    k3_gguf_close(&g);
}

/* ------------------------------------------------------------------ main */

int main(int argc, char **argv)
{
    const char *golden = argc > 1 ? argv[1] : "tests/fixtures/mxfp4_quant_golden.bin";
    run_name_map_tests();
    printf("== gguf mxfp4 requant goldens ==\n");
    if (run_requant_goldens(golden) != 0) return 1;
    run_synthetic_fixture();
    run_real_file_gate();

    if (fails) {
        printf("\nGGUF BIND: FAIL (%d)\n", fails);
        return 1;
    }
    printf("\nGGUF BIND: PASS\n");
    return 0;
}
